/*
 * Graded reader for "English for Seasonal Workers" (RU-only, A0-A1).
 * One running story about Ahmad (the L1 hero), split into chapters = lessons.
 *
 * Chapter N reuses ONLY the vocabulary of lessons 1..N + the function-word
 * whitelist (scripts/lib.js activeWhitelist). A few NEW words per chapter are a
 * conscious, dosed addition: each lives in `glossary` (<=5), is rendered BLUE in
 * the text, and opens a popup with transcription + RU + audio on tap. The reader
 * stays static, file://-safe, no runtime generation (offline, risk #1: unverified
 * English). Dual export like data.js / phrasebook.js.
 *
 * Exported as window.BOOKS = [ { id, emoji, title_ru, title_en, sub_ru, chapters:[...] } ]
 * — a shelf of books (one book now: "История Ахмада"; structure ready for more).
 * Each chapter:
 * Schema: chapter = {
 *   id,                 // == lesson id (unlock gate: store.done[id])
 *   emoji, title_ru, title_en,
 *   sentences: [ { en, ru } ],       // body = lessons 1..N vocab + whitelist + glossary[].en
 *   glossary:  [ { en, transcr, ru, pn } ],   // <=5; these tokens are coloured blue
 *   quiz:      [ { q_ru, opts_ru:[4], c } ]   // 2-3 RU comprehension questions, all Russian
 * } ]
 *
 * Glossary transcription is written by hand per the app's Cyrillic conventions
 * (verify-transcr only covers lesson words[], not the reader). IPA verified
 * against Wiktionary / Cambridge (RP).
 *
 * v1 = proof of 3 chapters (L1-L2-L3) only, NOT all 15 — conscious owner override
 * pending the live A0 test B (priority #1). See plans/2026-06-22-reading-book-feature.md.
 */
(function (root) {
  const READER = [
    {
      id: 1,
      emoji: "✈️",
      title_ru: "Ахмад приезжает",
      title_en: "Ahmad arrives",
      sentences: [
        { en: "Hello! I am Ahmad.", ru: "Привет! Я — Ахмад." },
        { en: "I am from Uzbekistan.", ru: "Я из Узбекистана." },
        { en: "I am a worker.", ru: "Я рабочий." },
        { en: "This is Britain.", ru: "Это Британия." },
        { en: "This is a big farm.", ru: "Это большая ферма." },
        { en: "Tom is the manager.", ru: "Том — менеджер." },
        { en: "He is British.", ru: "Он британец." },
        { en: '"Good morning, Ahmad! Welcome!"', ru: "«Доброе утро, Ахмад! Добро пожаловать!»" },
        { en: "Ahmad is a new picker.", ru: "Ахмад — новый сборщик." },
        { en: "Anna is a packer.", ru: "Анна — упаковщица." },
        { en: "She is from Kazakhstan.", ru: "Она из Казахстана." },
        { en: "Anna and Ahmad are a team.", ru: "Анна и Ахмад — одна команда." },
        { en: "Ahmad is happy.", ru: "Ахмад рад." },
        { en: '"You are welcome here, Ahmad!"', ru: "«Тебе здесь рады, Ахмад!»" },
      ],
      glossary: [
        { en: "big", transcr: "биг", ru: "большой", pn: "/bɪɡ/" },
        { en: "new", transcr: "нью", ru: "новый", pn: "/njuː/" },
        { en: "happy", transcr: "хэпи", ru: "рад, счастлив", pn: "/ˈhæpi/" },
        { en: "here", transcr: "хиэ", ru: "здесь", pn: "/hɪə/" },
      ],
      quiz: [
        { q_ru: "Откуда приехал Ахмад?", opts_ru: ["Из Узбекистана", "Из Британии", "Из Казахстана", "Из Таджикистана"], c: 0 },
        { q_ru: "Кто такой Том?", opts_ru: ["Менеджер", "Сборщик", "Водитель", "Механик"], c: 0 },
        { q_ru: "Кем работает Ахмад?", opts_ru: ["Сборщик (picker)", "Упаковщик (packer)", "Водитель (driver)", "Уборщик (cleaner)"], c: 0 },
      ],
    },
    {
      id: 2,
      emoji: "👨‍👩‍👦",
      title_ru: "Семья и друзья Ахмада",
      title_en: "Ahmad's family and friends",
      sentences: [
        { en: "This is my family.", ru: "Это моя семья." },
        { en: "This is a photo.", ru: "Это фото." },
        { en: "My wife is Fatima.", ru: "Моя жена — Фатима." },
        { en: "She is from Uzbekistan.", ru: "Она из Узбекистана." },
        { en: "This is my son, Ali.", ru: "Это мой сын, Али." },
        { en: "He is a baby.", ru: "Он малыш." },
        { en: "Sara is my colleague.", ru: "Сара — моя коллега." },
        { en: "She is a cleaner.", ru: "Она уборщица." },
        { en: "John is my friend.", ru: "Джон — мой друг." },
        { en: "He is a mechanic.", ru: "Он механик." },
        { en: "This is my locker.", ru: "Это мой шкафчик." },
        { en: "My badge is here.", ru: "Мой бейдж здесь." },
        { en: "Sara and John are good colleagues.", ru: "Сара и Джон — хорошие коллеги." },
      ],
      glossary: [
        { en: "photo", transcr: "фоутоу", ru: "фото", pn: "/ˈfəʊtəʊ/" },
        { en: "here", transcr: "хиэ", ru: "здесь", pn: "/hɪə/" },
      ],
      quiz: [
        { q_ru: "Как зовут жену Ахмада?", opts_ru: ["Фатима", "Анна", "Сара", "Аиша"], c: 0 },
        { q_ru: "Кто такой Али?", opts_ru: ["Сын Ахмада", "Брат Ахмада", "Друг Ахмада", "Менеджер"], c: 0 },
        { q_ru: "Кем работает Сара?", opts_ru: ["Уборщица (cleaner)", "Механик (mechanic)", "Упаковщица (packer)", "Менеджер (manager)"], c: 0 },
      ],
    },
    {
      id: 3,
      emoji: "🧰",
      title_ru: "Вещи на ферме",
      title_en: "Things on the farm",
      sentences: [
        { en: "Ahmad is a picker.", ru: "Ахмад — сборщик." },
        { en: "This is his job.", ru: "Это его работа." },
        { en: "Tom is the manager.", ru: "Том — менеджер." },
        { en: "This is a crate.", ru: "Это ящик." },
        { en: "These are punnets.", ru: "Это корзинки (для ягод)." },
        { en: "These punnets are small.", ru: "Эти корзинки маленькие." },
        { en: "This is a trolley.", ru: "Это тележка." },
        { en: "That is a ladder.", ru: "То — лестница." },
        { en: "These are tools.", ru: "Это инструменты." },
        { en: "This is a knife.", ru: "Это нож." },
        { en: "The knife is sharp.", ru: "Нож острый." },
        { en: '"Be careful, Ahmad!"', ru: "«Осторожно, Ахмад!»" },
        { en: "That is a hammer.", ru: "То — молоток." },
        { en: "That is a saw.", ru: "То — пила." },
        { en: "Those are boxes.", ru: "Те — коробки." },
        { en: "Ahmad is a good picker.", ru: "Ахмад — хороший сборщик." },
        { en: '"You are a good worker, Ahmad!"', ru: "«Ты хороший работник, Ахмад!»" },
      ],
      glossary: [
        { en: "small", transcr: "смол", ru: "маленький", pn: "/smɔːl/" },
        { en: "sharp", transcr: "шарп", ru: "острый", pn: "/ʃɑːp/" },
        { en: "careful", transcr: "кэафул", ru: "осторожный, осторожно", pn: "/ˈkeəfəl/" },
      ],
      quiz: [
        { q_ru: "Кем работает Ахмад?", opts_ru: ["Сборщик (picker)", "Механик (mechanic)", "Менеджер (manager)", "Водитель (driver)"], c: 0 },
        { q_ru: "Какой нож?", opts_ru: ["Острый", "Тупой", "Большой", "Старый"], c: 0 },
        { q_ru: "Что Том сказал Ахмаду в конце?", opts_ru: ["Ты хороший работник", "Осторожно", "Доброе утро", "До свидания"], c: 0 },
      ],
    },
    {
      id: 4,
      emoji: "⏰",
      title_ru: "Рабочий день",
      title_en: "A work day",
      sentences: [
        { en: "It is Monday.", ru: "Сегодня понедельник." },
        { en: "It is morning.", ru: "Сейчас утро." },
        { en: "It is seven o'clock.", ru: "Семь часов." },
        { en: "Ahmad is a picker.", ru: "Ахмад — сборщик." },
        { en: "Today is a good day.", ru: "Сегодня хороший день." },
        { en: '"Good morning, Ahmad!"', ru: "«Доброе утро, Ахмад!»" },
        { en: "Ahmad is fast.", ru: "Ахмад быстрый." },
        { en: "The day is long.", ru: "День длинный." },
        { en: "It is half past three.", ru: "Половина четвёртого." },
        { en: "It is Friday.", ru: "Сегодня пятница." },
        { en: "This is a payslip.", ru: "Это расчётный лист (payslip)." },
        { en: "It is my money.", ru: "Это мои деньги." },
        { en: "It is a good week.", ru: "Хорошая неделя." },
      ],
      glossary: [
        { en: "fast", transcr: "фаст", ru: "быстрый", pn: "/fɑːst/" },
        { en: "long", transcr: "лонг", ru: "длинный", pn: "/lɒŋ/" },
      ],
      quiz: [
        { q_ru: "Какой сегодня день в начале истории?", opts_ru: ["Понедельник", "Пятница", "Среда", "Воскресенье"], c: 0 },
        { q_ru: "Что Ахмад получает в пятницу?", opts_ru: ["Расчётный лист (payslip)", "Ящик", "Трактор", "Ключ"], c: 0 },
        { q_ru: "Какой Ахмад работник?", opts_ru: ["Быстрый", "Медленный", "Усталый", "Старый"], c: 0 },
      ],
    },
    {
      id: 5,
      emoji: "🗺️",
      title_ru: "Где что на ферме",
      title_en: "Around the farm",
      sentences: [
        { en: "This is the camp.", ru: "Это лагерь (кэмп)." },
        { en: "It is a big camp.", ru: "Это большой лагерь." },
        { en: '"Where is the canteen?"', ru: "«Где столовая?»" },
        { en: "It is near the gate.", ru: "Она рядом с воротами." },
        { en: "The shop is on the left.", ru: "Магазин слева." },
        { en: "The toilet is on the right.", ru: "Туалет справа." },
        { en: '"Where is the office?"', ru: "«Где офис?»" },
        { en: "It is behind the shed.", ru: "Он за сараем." },
        { en: "Tom is in the office.", ru: "Том в офисе." },
        { en: "This is the road.", ru: "Это дорога." },
        { en: "A tractor is on the road.", ru: "Трактор на дороге." },
        { en: "The field is near the river.", ru: "Поле рядом с рекой." },
        { en: "A tree is on the hill.", ru: "Дерево на холме." },
        { en: '"Thank you, Tom!"', ru: "«Спасибо, Том!»" },
      ],
      glossary: [
        { en: "big", transcr: "биг", ru: "большой", pn: "/bɪɡ/" },
        { en: "left", transcr: "лэфт", ru: "слева, левый", pn: "/left/" },
        { en: "right", transcr: "райт", ru: "справа, правый", pn: "/raɪt/" },
      ],
      quiz: [
        { q_ru: "Где столовая?", opts_ru: ["Рядом с воротами", "На холме", "За рекой", "В офисе"], c: 0 },
        { q_ru: "Что находится слева?", opts_ru: ["Магазин", "Туалет", "Офис", "Трактор"], c: 0 },
        { q_ru: "Где Том?", opts_ru: ["В офисе", "В столовой", "На дороге", "На холме"], c: 0 },
      ],
    },
    {
      id: 6,
      emoji: "🔁",
      title_ru: "Каждый день",
      title_en: "Every day",
      sentences: [
        { en: "Ahmad is a picker.", ru: "Ахмад — сборщик." },
        { en: "He works on the farm.", ru: "Он работает на ферме." },
        { en: "He works every day.", ru: "Он работает каждый день." },
        { en: "Ahmad starts work.", ru: "Ахмад начинает работу." },
        { en: "He picks berries.", ru: "Он собирает ягоды." },
        { en: "He works fast.", ru: "Он работает быстро." },
        { en: "Ahmad fills the crate.", ru: "Ахмад наполняет ящик." },
        { en: "He carries it.", ru: "Он несёт его." },
        { en: "Tom checks them.", ru: "Том проверяет их." },
        { en: "Tom gives him a crate.", ru: "Том даёт ему ящик." },
        { en: "They pick berries.", ru: "Они собирают ягоды." },
        { en: "Ahmad packs the berries.", ru: "Ахмад упаковывает ягоды." },
        { en: "He weighs them.", ru: "Он их взвешивает." },
        { en: '"Thank you, Ahmad!"', ru: "«Спасибо, Ахмад!»" },
      ],
      glossary: [
        { en: "every", transcr: "эври", ru: "каждый", pn: "/ˈɛvri/" },
        { en: "fast", transcr: "фаст", ru: "быстро", pn: "/fɑːst/" },
      ],
      quiz: [
        { q_ru: "Как часто Ахмад работает?", opts_ru: ["Каждый день", "Никогда", "Иногда", "Один раз"], c: 0 },
        { q_ru: "Что собирает Ахмад?", opts_ru: ["Ягоды (berries)", "Картошку (potato)", "Рыбу (fish)", "Хлеб (bread)"], c: 0 },
        { q_ru: "Кто проверяет ящики?", opts_ru: ["Том", "Сара", "Джон", "Анна"], c: 0 },
      ],
    },
    // ── Chapter 7 ──────────────────────────────────────────────────────────
    {
      id: 7,
      emoji: "🌧️",
      title_ru: "Что сейчас происходит",
      title_en: "What is happening now",
      sentences: [
        { en: "It is morning.", ru: "Сейчас утро." },
        { en: "It is raining.", ru: "Идёт дождь." },
        { en: "Ahmad is walking to the field.", ru: "Ахмад идёт в поле." },
        { en: "He is walking slowly.", ru: "Он идёт медленно." },
        { en: "Tom is standing near the gate.", ru: "Том стоит рядом с воротами." },
        { en: "Tom is talking to the team.", ru: "Том разговаривает с командой." },
        { en: "Anna is picking berries.", ru: "Анна собирает ягоды." },
        { en: "She is working quickly.", ru: "Она работает быстро." },
        { en: "Ahmad is filling the crate.", ru: "Ахмад наполняет ящик." },
        { en: "He is working in the rain.", ru: "Он работает под дождём." },
        { en: "Tom is helping Ahmad.", ru: "Том помогает Ахмаду." },
        { en: "Sara is sweeping the camp.", ru: "Сара подметает лагерь." },
        { en: '"What are you doing, Ahmad?"', ru: "«Что ты делаешь, Ахмад?»" },
        { en: '"I am filling the crate, Tom!"', ru: "«Я наполняю ящик, Том!»" },
      ],
      glossary: [
        { en: "slowly", transcr: "слоули", ru: "медленно", pn: "/ˈsləʊli/" },
        { en: "quickly", transcr: "куикли", ru: "быстро", pn: "/ˈkwɪkli/" },
      ],
      quiz: [
        { q_ru: "Что делает Ахмад в начале истории?", opts_ru: ["Идёт в поле", "Стоит у ворот", "Наполняет ящик", "Подметает лагерь"], c: 0 },
        { q_ru: "Кто работает быстро?", opts_ru: ["Том", "Анна", "Ахмад", "Сара"], c: 1 },
        { q_ru: "Что говорит Ахмад Тому в конце?", opts_ru: ["Я иду в поле", "Я помогаю Тому", "Я наполняю ящик", "Я подметаю лагерь"], c: 2 },
      ],
    },
    // ── Chapter 8 ──────────────────────────────────────────────────────────
    {
      id: 8,
      emoji: "🦺",
      title_ru: "Одежда и цвета",
      title_en: "Clothes and colours",
      sentences: [
        { en: "It is morning.", ru: "Сейчас утро." },
        { en: "Ahmad has a yellow vest.", ru: "У Ахмада жёлтый жилет." },
        { en: "He has green wellies.", ru: "У него зелёные резиновые сапоги." },
        { en: "He has orange gloves.", ru: "У него оранжевые перчатки." },
        { en: "His jacket is blue.", ru: "Его куртка синяя." },
        { en: "His jacket is warm.", ru: "Его куртка тёплая." },
        { en: "Tom has a white cap.", ru: "У Тома белая кепка." },
        { en: "Anna has a red coat.", ru: "У Анны красное пальто." },
        { en: "Ahmad has a helmet.", ru: "У Ахмада каска." },
        { en: "The helmet is safe.", ru: "Каска защищает." },
        { en: "He has goggles.", ru: "У него защитные очки." },
        { en: '"Do you have your mask, Ahmad?"', ru: "«У тебя есть маска, Ахмад?»" },
        { en: '"Yes! I have my mask."', ru: "«Да! У меня маска.»" },
        { en: "Ahmad is a good worker.", ru: "Ахмад — хороший рабочий." },
      ],
      glossary: [
        { en: "warm", transcr: "уорм", ru: "тёплый", pn: "/wɔːm/" },
        { en: "safe", transcr: "сэйф", ru: "безопасный, защищает", pn: "/seɪf/" },
      ],
      quiz: [
        { q_ru: "Какого цвета жилет Ахмада?", opts_ru: ["Жёлтый", "Красный", "Синий", "Белый"], c: 0 },
        { q_ru: "Что защищает голову Ахмада?", opts_ru: ["Кепка (cap)", "Каска (helmet)", "Очки (goggles)", "Маска (mask)"], c: 1 },
        { q_ru: "Какая куртка у Ахмада?", opts_ru: ["Красная и тёплая", "Белая и холодная", "Синяя и тёплая", "Жёлтая и новая"], c: 2 },
      ],
    },
    // ── Chapter 9 ──────────────────────────────────────────────────────────
    {
      id: 9,
      emoji: "🛏️",
      title_ru: "Комната Ахмада",
      title_en: "Ahmad's room",
      sentences: [
        { en: "This is Ahmad's room.", ru: "Это комната Ахмада." },
        { en: "The room is small.", ru: "Комната маленькая." },
        { en: "There is a bed.", ru: "Есть кровать." },
        { en: "The bed is cold.", ru: "Кровать холодная." },
        { en: "There is a heater.", ru: "Есть обогреватель." },
        { en: "The heater is broken.", ru: "Обогреватель сломан." },
        { en: "Ahmad is cold.", ru: "Ахмаду холодно." },
        { en: "There is a blanket.", ru: "Есть одеяло." },
        { en: "The room is dirty.", ru: "Комната грязная." },
        { en: "There is a mug.", ru: "Есть кружка." },
        { en: "The mug is empty.", ru: "Кружка пустая." },
        { en: "Ahmad's key is on the shelf.", ru: "Ключ Ахмада лежит на полке." },
        { en: '"Tom! The heater is not working!"', ru: "«Том! Обогреватель не работает!»" },
        { en: '"I am sorry, Ahmad!"', ru: "«Мне жаль, Ахмад!»" },
        { en: "Tom fixes the heater.", ru: "Том чинит обогреватель." },
        { en: "The room is warm now.", ru: "Теперь комната тёплая." },
      ],
      glossary: [
        { en: "small", transcr: "смол", ru: "маленький", pn: "/smɔːl/" },
        { en: "dirty", transcr: "дёрти", ru: "грязный", pn: "/ˈdɜːti/" },
        { en: "warm", transcr: "уорм", ru: "тёплый", pn: "/wɔːm/" },
      ],
      quiz: [
        { q_ru: "Почему Ахмаду холодно?", opts_ru: ["Сломан обогреватель (heater)", "Нет одеяла", "Открыто окно", "Холодный душ"], c: 0 },
        { q_ru: "Что лежит на полке?", opts_ru: ["Кружка (mug)", "Ключ Ахмада (key)", "Одеяло (blanket)", "Вилка (fork)"], c: 1 },
        { q_ru: "Какой стала комната в конце?", opts_ru: ["Грязной и холодной", "Маленькой и пустой", "Тёмной и сломанной", "Тёплой"], c: 3 },
      ],
    },
    // ── Chapter 10 ─────────────────────────────────────────────────────────
    {
      id: 10,
      emoji: "🛒",
      title_ru: "В магазине",
      title_en: "At the shop",
      sentences: [
        { en: "It is Saturday.", ru: "Сегодня суббота." },
        { en: "Ahmad is in the shop.", ru: "Ахмад в магазине." },
        { en: "He has a shopping list.", ru: "У него список покупок." },
        { en: '"I would like some bread."', ru: "«Я бы хотел хлеба.»" },
        { en: '"I would like some milk."', ru: "«Я бы хотел молока.»" },
        { en: "He takes some rice.", ru: "Он берёт рис." },
        { en: "He takes some tea.", ru: "Он берёт чай." },
        { en: "The bread is fresh.", ru: "Хлеб свежий." },
        { en: '"How much is the cheese?"', ru: "«Сколько стоит сыр?»" },
        { en: "The cheese is two pounds.", ru: "Сыр стоит два фунта." },
        { en: '"How much is the honey?"', ru: "«Сколько стоит мёд?»" },
        { en: "The honey is sweet.", ru: "Мёд сладкий." },
        { en: "The food is cheap.", ru: "Еда дешёвая." },
        { en: "Ahmad gives the money.", ru: "Ахмад отдаёт деньги." },
        { en: '"Thank you!"', ru: "«Спасибо!»" },
      ],
      glossary: [
        { en: "fresh", transcr: "фрэш", ru: "свежий", pn: "/freʃ/" },
        { en: "sweet", transcr: "суит", ru: "сладкий", pn: "/swiːt/" },
        { en: "cheap", transcr: "чип", ru: "дешёвый", pn: "/tʃiːp/" },
      ],
      quiz: [
        { q_ru: "Где Ахмад в этой главе?", opts_ru: ["В магазине", "В поле", "В офисе", "В столовой"], c: 0 },
        { q_ru: "Что Ахмад берёт?", opts_ru: ["Рис и чай (rice, tea)", "Мясо и рыбу (meat, fish)", "Яйца и лук (egg, onion)", "Суп и соль (soup, salt)"], c: 0 },
        { q_ru: "Какая еда в магазине?", opts_ru: ["Дешёвая", "Дорогая", "Старая", "Горячая"], c: 0 },
      ],
    },
    // ── Chapter 11 ─────────────────────────────────────────────────────────
    {
      id: 11,
      emoji: "🚌",
      title_ru: "В город на автобусе",
      title_en: "To town by bus",
      sentences: [
        { en: "It is Sunday.", ru: "Сегодня воскресенье." },
        { en: "Ahmad is not at work today.", ru: "Сегодня Ахмад не на работе." },
        { en: "He is going to town.", ru: "Он едет в город." },
        { en: "The town is far.", ru: "Город далеко." },
        { en: "He is at the bus stop.", ru: "Он на автобусной остановке." },
        { en: "There is a queue.", ru: "Есть очередь." },
        { en: "Ahmad is in the queue.", ru: "Ахмад в очереди." },
        { en: '"Which bus is it?"', ru: "«Какой это автобус?»" },
        { en: "The bus is here.", ru: "Автобус здесь." },
        { en: '"How much is the ticket?"', ru: "«Сколько стоит билет?»" },
        { en: "The ticket is two pounds.", ru: "Билет стоит два фунта." },
        { en: "Ahmad has a seat.", ru: "У Ахмада есть место." },
        { en: "This seat is good.", ru: "Это место хорошее." },
        { en: "The journey is good.", ru: "Поездка хорошая." },
        { en: "Ahmad is in town now.", ru: "Теперь Ахмад в городе." },
      ],
      glossary: [
        { en: "town", transcr: "таун", ru: "город", pn: "/taʊn/" },
        { en: "far", transcr: "фа", ru: "далеко", pn: "/fɑː/" },
      ],
      quiz: [
        { q_ru: "Куда едет Ахмад?", opts_ru: ["В город", "В поле", "На ферму", "В лагерь"], c: 0 },
        { q_ru: "На чём едет Ахмад?", opts_ru: ["На автобусе (bus)", "На поезде (train)", "На такси (taxi)", "На лодке (boat)"], c: 0 },
        { q_ru: "Сколько стоит билет?", opts_ru: ["Два фунта", "Один фунт", "Пять фунтов", "Десять фунтов"], c: 0 },
      ],
    },
    // ── Chapter 12 ─────────────────────────────────────────────────────────
    {
      id: 12,
      emoji: "📋",
      title_ru: "Анкета в офисе",
      title_en: "A form in the office",
      sentences: [
        { en: "It is October.", ru: "Сейчас октябрь." },
        { en: "Ahmad is in the office.", ru: "Ахмад в офисе." },
        { en: "Tom has a form.", ru: "У Тома анкета." },
        { en: '"When is your birthday, Ahmad?"', ru: "«Когда у тебя день рождения, Ахмад?»" },
        { en: '"My birthday is in May."', ru: "«Мой день рождения в мае.»" },
        { en: "Ahmad fills in the form.", ru: "Ахмад заполняет анкету." },
        { en: "This is his address.", ru: "Это его адрес." },
        { en: "This is his postcode.", ru: "Это его почтовый индекс." },
        { en: "He has a contract.", ru: "У него контракт." },
        { en: "It is his first contract.", ru: "Это его первый контракт." },
        { en: '"The year was good."', ru: "«Год был хороший.»" },
        { en: '"We were in the field."', ru: "«Мы были в поле.»" },
        { en: "The work was good.", ru: "Работа была хорошая." },
        { en: "Ahmad was a good worker.", ru: "Ахмад был хорошим работником." },
        { en: "The farm is good.", ru: "Ферма хорошая." },
      ],
      glossary: [
        { en: "first", transcr: "фёст", ru: "первый", pn: "/fɜːst/" },
      ],
      quiz: [
        { q_ru: "Когда у Ахмада день рождения?", opts_ru: ["В мае", "В январе", "В октябре", "В декабре"], c: 0 },
        { q_ru: "Что Ахмад заполняет в офисе?", opts_ru: ["Анкету (form)", "Список (list)", "Билет (ticket)", "Письмо"], c: 0 },
        { q_ru: "Каким был год для Ахмада?", opts_ru: ["Хорошим", "Плохим", "Холодным", "Коротким"], c: 0 },
      ],
    },
    // ── Chapter 13 ─────────────────────────────────────────────────────────
    {
      id: 13,
      emoji: "📅",
      title_ru: "Прошлая смена",
      title_en: "Yesterday's shift",
      sentences: [
        { en: "Yesterday was Monday.", ru: "Вчера был понедельник." },
        { en: "Ahmad started work early.", ru: "Ахмад начал работу рано." },
        { en: "He worked hard.", ru: "Он работал усердно." },
        { en: "He picked berries.", ru: "Он собирал ягоды." },
        { en: "Then he packed them.", ru: "Потом он их упаковал." },
        { en: "He collected the crates.", ru: "Он собрал ящики." },
        { en: "Tom drove the tractor.", ru: "Том водил трактор." },
        { en: "Tom asked Ahmad.", ru: "Том спросил Ахмада." },
        { en: "Ahmad answered Tom.", ru: "Ахмад ответил Тому." },
        { en: "He bought lunch.", ru: "Он купил обед." },
        { en: "He ate some bread.", ru: "Он съел хлеба." },
        { en: "He drank some tea.", ru: "Он выпил чая." },
        { en: "Then he finished late.", ru: "Потом он закончил поздно." },
        { en: "He left the field.", ru: "Он ушёл с поля." },
        { en: "It was a hard shift.", ru: "Это была тяжёлая смена." },
        { en: "Ahmad did good work.", ru: "Ахмад хорошо поработал." },
      ],
      glossary: [
        { en: "then", transcr: "зэн", ru: "потом, затем", pn: "/ðen/" },
      ],
      quiz: [
        { q_ru: "Когда была эта смена?", opts_ru: ["Вчера", "Сегодня", "Завтра", "На той неделе"], c: 0 },
        { q_ru: "Что Ахмад делал на смене?", opts_ru: ["Собирал ягоды (picked)", "Водил трактор (drove)", "Чинил машину (repaired)", "Спал (slept)"], c: 0 },
        { q_ru: "Какой была смена?", opts_ru: ["Тяжёлая (hard)", "Лёгкая", "Короткая", "Скучная"], c: 0 },
      ],
    },
    // ── Chapter 14 ─────────────────────────────────────────────────────────
    {
      id: 14,
      emoji: "🩺",
      title_ru: "У врача",
      title_en: "At the doctor",
      sentences: [
        { en: "Ahmad is ill.", ru: "Ахмад болен." },
        { en: "His arm hurts.", ru: "У него болит рука." },
        { en: "He cannot work today.", ru: "Он не может работать сегодня." },
        { en: "He cannot lift the crate.", ru: "Он не может поднять ящик." },
        { en: '"I have a pain in my arm."', ru: "«У меня боль в руке.»" },
        { en: "Ahmad has an appointment.", ru: "У Ахмада приём (запись)." },
        { en: "He is at the doctor.", ru: "Он у врача." },
        { en: "The doctor is kind.", ru: "Врач добрый." },
        { en: "The nurse helps him.", ru: "Медсестра помогает ему." },
        { en: '"Can you move your arm?"', ru: "«Можете подвигать рукой?»" },
        { en: '"I can move it."', ru: "«Я могу подвигать ею.»" },
        { en: "The doctor checks his arm.", ru: "Врач осматривает его руку." },
        { en: '"You can rest today."', ru: "«Сегодня можете отдыхать.»" },
        { en: "The next day, Ahmad is better.", ru: "На следующий день Ахмаду лучше." },
        { en: "He is happy.", ru: "Он счастлив." },
        { en: "He can work again.", ru: "Он снова может работать." },
      ],
      glossary: [
        { en: "kind", transcr: "кайнд", ru: "добрый", pn: "/kaɪnd/" },
        { en: "again", transcr: "эгэн", ru: "снова, опять", pn: "/əˈɡen/" },
      ],
      quiz: [
        { q_ru: "Что у Ахмада болит?", opts_ru: ["Рука (arm)", "Нога (leg)", "Зуб (tooth)", "Глаз (eye)"], c: 0 },
        { q_ru: "К кому идёт Ахмад?", opts_ru: ["К врачу (doctor)", "К менеджеру (manager)", "К механику (mechanic)", "К соседу (neighbour)"], c: 0 },
        { q_ru: "Что Ахмад может делать в конце?", opts_ru: ["Снова работать", "Поднять ящик", "Водить трактор", "Бежать"], c: 0 },
      ],
    },
    // ── Chapter 15 ─────────────────────────────────────────────────────────
    {
      id: 15,
      emoji: "🎉",
      title_ru: "Конец сезона",
      title_en: "The end of the season",
      sentences: [
        { en: "It is the last day.", ru: "Это последний день." },
        { en: "The work is finished.", ru: "Работа закончена." },
        { en: "Ahmad is free today.", ru: "Сегодня Ахмад свободен." },
        { en: "He is happy.", ru: "Он счастлив." },
        { en: "All his friends are here.", ru: "Все его друзья здесь." },
        { en: "They have a party.", ru: "У них вечеринка." },
        { en: '"I like this music!"', ru: "«Мне нравится эта музыка!»" },
        { en: '"I love football!"', ru: "«Я люблю футбол!»" },
        { en: '"I want to dance!"', ru: "«Я хочу танцевать!»" },
        { en: "Sara cooks food.", ru: "Сара готовит еду." },
        { en: "The food is lovely.", ru: "Еда прекрасная." },
        { en: '"This is fun!"', ru: "«Это весело!»" },
        { en: '"Cheers, mate!"', ru: "«Будь здоров, дружище!»" },
        { en: '"I love the farm!"', ru: "«Я люблю ферму!»" },
        { en: "It is a great day.", ru: "Это отличный день." },
        { en: '"Goodbye, friends!"', ru: "«До свидания, друзья!»" },
      ],
      glossary: [
        { en: "all", transcr: "ол", ru: "все, всё", pn: "/ɔːl/" },
      ],
      quiz: [
        { q_ru: "Какой это день?", opts_ru: ["Последний день сезона", "Первый день", "Обычная смена", "Выходной в середине"], c: 0 },
        { q_ru: "Что любит Ахмад?", opts_ru: ["Музыку и футбол", "Дождь и холод", "Тяжёлую работу", "Тишину"], c: 0 },
        { q_ru: "Что делают друзья в конце?", opts_ru: ["У них вечеринка", "Они работают", "Они спят", "Они уезжают утром"], c: 0 },
      ],
    },
    {
      id: 16,
      emoji: "🌦️",
      title_ru: "Второй сезон",
      title_en: "The second season",
      sentences: [
        { en: "Ahmad is here again.", ru: "Ахмад снова здесь." },
        { en: "This is his second season.", ru: "Это его второй сезон." },
        { en: "He is happy to work.", ru: "Он рад работать." },
        { en: "Tom is the manager again.", ru: "Том снова менеджер." },
        { en: '"Hello, Ahmad! Welcome!"', ru: "«Привет, Ахмад! Добро пожаловать!»" },
        { en: "Ahmad looks at the sky.", ru: "Ахмад смотрит на небо." },
        { en: "The sky is grey today.", ru: "Небо сегодня серое." },
        { en: "He checks the weather forecast.", ru: "Он проверяет прогноз погоды." },
        { en: '"It is going to rain tomorrow."', ru: "«Завтра будет дождь.»" },
        { en: '"Tomorrow is going to be cold."', ru: "«Завтра будет холодно.»" },
        { en: "Ahmad is going to take his jacket.", ru: "Ахмад возьмёт свою куртку." },
        { en: '"I am going to work in the shed."', ru: "«Я буду работать в сарае.»" },
        { en: "The team is going to pick berries.", ru: "Команда будет собирать ягоды." },
        { en: '"This season is going to be good."', ru: "«Этот сезон будет хорошим.»" },
        { en: '"I am ready to work!"', ru: "«Я готов работать!»" },
      ],
      glossary: [
        { en: "again", transcr: "эгэн", ru: "снова, опять", pn: "/əˈɡen/" },
        { en: "second", transcr: "сэкэнд", ru: "второй", pn: "/ˈsekənd/" },
        { en: "sky", transcr: "скай", ru: "небо", pn: "/skaɪ/" },
      ],
      quiz: [
        { q_ru: "Какой сезон на ферме у Ахмада?", opts_ru: ["Второй", "Первый", "Третий", "Последний"], c: 0 },
        { q_ru: "Что говорит прогноз погоды на завтра?", opts_ru: ["Будет дождь и холодно", "Будет жарко и солнечно", "Будет снег весь день", "Туман и ветер"], c: 0 },
        { q_ru: "Что Ахмад собирается взять с собой?", opts_ru: ["Куртку", "Зонт", "Сапоги", "Шапку"], c: 0 },
      ],
    },
    {
      id: 17,
      emoji: "📏",
      title_ru: "Новые рабочие",
      title_en: "The new workers",
      sentences: [
        { en: "It is a new season.", ru: "Это новый сезон." },
        { en: "Some workers are new this year.", ru: "В этом году некоторые рабочие — новенькие." },
        { en: "Ahmad is not new now.", ru: "Ахмад теперь не новичок." },
        { en: "He helps the new workers learn.", ru: "Он помогает новым рабочим учиться." },
        { en: "A full crate is heavier than an empty crate.", ru: "Полный ящик тяжелее пустого ящика." },
        { en: "Ahmad lifts the heavy crate.", ru: "Ахмад поднимает тяжёлый ящик." },
        { en: '"You are the best picker, Ahmad!"', ru: "«Ты лучший сборщик, Ахмад!»" },
        { en: "The new workers are slower today.", ru: "Новые рабочие сегодня медленнее." },
        { en: "They learn from Ahmad.", ru: "Они учатся у Ахмада." },
        { en: "This work is easy now.", ru: "Эта работа теперь лёгкая." },
        { en: "The new workers are quiet and friendly.", ru: "Новые рабочие тихие и дружелюбные." },
        { en: "Ahmad is happy to help them.", ru: "Ахмад рад им помочь." },
        { en: '"A good team is strong."', ru: "«Хорошая команда — сильная.»" },
        { en: '"I am ready to work hard!"', ru: "«Я готов работать усердно!»" },
      ],
      glossary: [
        { en: "new", transcr: "нью", ru: "новый", pn: "/njuː/" },
        { en: "learn", transcr: "лён", ru: "учиться", pn: "/lɜːn/" },
      ],
      quiz: [
        { q_ru: "Кто в этом сезоне новенькие?", opts_ru: ["Некоторые рабочие", "Ахмад", "Том", "Менеджер"], c: 0 },
        { q_ru: "Что тяжелее?", opts_ru: ["Полный ящик", "Пустая коробка", "Перчатки", "Бейдж"], c: 0 },
        { q_ru: "Что Том говорит об Ахмаде?", opts_ru: ["Он лучший сборщик", "Он новичок", "Он медленный", "Он устал"], c: 0 },
      ],
    },
    {
      id: 18,
      emoji: "🚜",
      title_ru: "На тракторе",
      title_en: "On the tractor",
      sentences: [
        { en: "This season Ahmad drives the tractor.", ru: "В этом сезоне Ахмад водит трактор." },
        { en: "Last year he could not drive it.", ru: "В прошлом году он не мог его водить." },
        { en: "Now he can drive carefully.", ru: "Теперь он водит аккуратно." },
        { en: "First, he checks the engine.", ru: "Сначала он проверяет двигатель." },
        { en: "Ahmad checks the oil and the fuel.", ru: "Ахмад проверяет масло и топливо." },
        { en: "The engine starts easily today.", ru: "Двигатель сегодня заводится легко." },
        { en: "Ahmad drives slowly and safely.", ru: "Ахмад едет медленно и осторожно." },
        { en: "He could not turn the tractor well last year.", ru: "В прошлом году он не мог хорошо поворачивать трактор." },
        { en: "Now he can do it well.", ru: "Теперь он может это хорошо." },
        { en: '"Drive carefully near the gate!"', ru: "«Веди аккуратно у ворот!»" },
        { en: "The brake works well.", ru: "Тормоз работает хорошо." },
        { en: "John the mechanic helps Ahmad.", ru: "Джон-механик помогает Ахмаду." },
        { en: "Now Ahmad works carefully and safely.", ru: "Теперь Ахмад работает аккуратно и осторожно." },
        { en: '"You drive well, Ahmad!"', ru: "«Ты хорошо водишь, Ахмад!»" },
      ],
      glossary: [
        { en: "first", transcr: "фёст", ru: "сначала, первый", pn: "/fɜːst/" },
        { en: "slowly", transcr: "слоули", ru: "медленно", pn: "/ˈsləʊli/" },
      ],
      quiz: [
        { q_ru: "Что Ахмад делает в этом сезоне?", opts_ru: ["Водит трактор", "Готовит еду", "Едет в город", "Спит"], c: 0 },
        { q_ru: "Как Ахмад водит трактор?", opts_ru: ["Медленно и осторожно", "Быстро и опасно", "Плохо", "Громко"], c: 0 },
        { q_ru: "Кто помогает Ахмаду с двигателем?", opts_ru: ["Механик", "Медсестра", "Кассир", "Врач"], c: 0 },
      ],
    },
    {
      id: 19,
      emoji: "🩹",
      title_ru: "Болит спина",
      title_en: "A sore back",
      sentences: [
        { en: "It is a hard day on the farm.", ru: "Тяжёлый день на ферме." },
        { en: "Ahmad has got new gloves.", ru: "У Ахмада новые перчатки." },
        { en: "He works hard today.", ru: "Сегодня он много работает." },
        { en: "Now he has got a sore back.", ru: "Теперь у него болит спина." },
        { en: "His shoulder is sore.", ru: "Плечо тоже болит." },
        { en: "Ahmad is tired.", ru: "Ахмад устал." },
        { en: '"Have you got a problem?"', ru: "«У тебя проблема?»" },
        { en: '"I have got a sore back."', ru: "«У меня болит спина.»" },
        { en: '"Rest now, Ahmad."', ru: "«Отдохни сейчас, Ахмад.»" },
        { en: "The nurse checks his back.", ru: "Медсестра осматривает его спину." },
        { en: '"Have you got any pain here?"', ru: "«Здесь болит?»" },
        { en: '"Yes, I have got a pain in my back."', ru: "«Да, у меня болит спина.»" },
        { en: "Ahmad is still worried.", ru: "Ахмад всё ещё встревожен." },
        { en: '"You are going to be fine."', ru: "«Ты поправишься.»" },
        { en: "Now Ahmad is better.", ru: "Теперь Ахмаду лучше." },
      ],
      glossary: [
        { en: "new", transcr: "нью", ru: "новый", pn: "/njuː/" },
        { en: "still", transcr: "стил", ru: "всё ещё", pn: "/stɪl/" },
      ],
      quiz: [
        { q_ru: "Что болит у Ахмада?", opts_ru: ["Спина и плечо", "Голова", "Нога", "Рука"], c: 0 },
        { q_ru: "Что говорит Том Ахмаду?", opts_ru: ["Отдохни сейчас", "Работай быстрее", "Иди домой утром", "Неси ящик"], c: 0 },
        { q_ru: "Кто осматривает спину Ахмада?", opts_ru: ["Медсестра", "Менеджер", "Друг", "Водитель"], c: 0 },
      ],
    },
    {
      id: 20,
      emoji: "🛏️",
      title_ru: "Комната в кэмпе",
      title_en: "The room in the camp",
      sentences: [
        { en: "Ahmad has got a room in the camp.", ru: "У Ахмада комната в кэмпе." },
        { en: "It is his second season here.", ru: "Это его второй сезон здесь." },
        { en: "There is something in the cupboard.", ru: "В шкафу что-то есть." },
        { en: "Ahmad opens the cupboard.", ru: "Ахмад открывает шкаф." },
        { en: "There is a pillow and a sheet.", ru: "Там подушка и простыня." },
        { en: "There is nothing on the bed.", ru: "А на кровати ничего нет." },
        { en: '"Is there anything in the wardrobe?"', ru: "«Есть что-нибудь в платяном шкафу?»" },
        { en: "There is nothing in the wardrobe.", ru: "В платяном шкафу ничего нет." },
        { en: "His jacket is on the shelf.", ru: "Его куртка на полке." },
        { en: "The room is clean and tidy.", ru: "Комната чистая и опрятная." },
        { en: "There is a heater in the corner.", ru: "В углу обогреватель." },
        { en: "Everything is ready now.", ru: "Теперь всё готово." },
        { en: '"Everything is good here."', ru: "«Здесь всё хорошо.»" },
        { en: "Ahmad is happy in his room.", ru: "Ахмад рад в своей комнате." },
      ],
      glossary: [
        { en: "tidy", transcr: "тайди", ru: "опрятный, прибранный", pn: "/ˈtaɪdi/" },
        { en: "second", transcr: "сэкэнд", ru: "второй", pn: "/ˈsekənd/" },
      ],
      quiz: [
        { q_ru: "Что Ахмад находит в шкафу (cupboard)?", opts_ru: ["Подушку и простыню", "Ничего", "Куртку", "Обогреватель"], c: 0 },
        { q_ru: "Что в платяном шкафу (wardrobe)?", opts_ru: ["Ничего", "Подушка", "Одеяло", "Простыня"], c: 0 },
        { q_ru: "Какая комната у Ахмада?", opts_ru: ["Чистая и опрятная", "Грязная", "Холодная", "Пустая"], c: 0 },
      ],
    },
    {
      id: 21,
      emoji: "🏙️",
      title_ru: "В городе",
      title_en: "In town",
      sentences: [
        { en: "Today Ahmad is free.", ru: "Сегодня Ахмад свободен." },
        { en: "He takes the bus to town.", ru: "Он едет на автобусе в город." },
        { en: "Why does Ahmad go to town?", ru: "Зачем Ахмад едет в город?" },
        { en: "He is in town to buy food.", ru: "Он в городе, чтобы купить еду." },
        { en: "First, he walks to the bank to take money.", ru: "Сначала он идёт в банк снять деньги." },
        { en: "Then he walks to the supermarket.", ru: "Потом он идёт в супермаркет." },
        { en: "He buys bread, rice, and eggs.", ru: "Он покупает хлеб, рис и яйца." },
        { en: "Ahmad walks to the pharmacy to buy medicine.", ru: "Ахмад идёт в аптеку купить лекарство." },
        { en: "He visits the library to read.", ru: "Он заходит в библиотеку почитать." },
        { en: "Why does Ahmad walk to the cafe?", ru: "Зачем Ахмад идёт в кафе?" },
        { en: "He walks to the cafe to meet a friend.", ru: "Он идёт в кафе встретить друга." },
        { en: "They have tea and talk.", ru: "Они пьют чай и болтают." },
        { en: "Ahmad returns to the camp.", ru: "Ахмад возвращается в кэмп." },
        { en: '"It is a good day in town!"', ru: "«Хороший день в городе!»" },
      ],
      glossary: [
        { en: "first", transcr: "фёст", ru: "сначала, первый", pn: "/fɜːst/" },
        { en: "then", transcr: "зэн", ru: "потом, затем", pn: "/ðen/" },
      ],
      quiz: [
        { q_ru: "Зачем Ахмад едет в город?", opts_ru: ["Купить еду", "Спать", "Работать", "Отдыхать в поле"], c: 0 },
        { q_ru: "Зачем он идёт в банк?", opts_ru: ["Снять деньги", "Купить хлеб", "Встретить друга", "Почитать"], c: 0 },
        { q_ru: "Где Ахмад встречает друга?", opts_ru: ["В кафе", "В банке", "В аптеке", "В библиотеке"], c: 0 },
      ],
    },
    {
      id: 22,
      emoji: "🍳",
      title_ru: "Ужин с друзьями",
      title_en: "Dinner with friends",
      sentences: [
        { en: "It is the weekend.", ru: "Выходные." },
        { en: "Ahmad and his friends cook dinner.", ru: "Ахмад с друзьями готовят ужин." },
        { en: "First, Ahmad takes the food from the fridge.", ru: "Сначала Ахмад достаёт еду из холодильника." },
        { en: "They get the carrots and onions.", ru: "Они берут морковь и лук." },
        { en: "Anna peels the carrots.", ru: "Анна чистит морковь." },
        { en: "Ahmad slices the cabbage.", ru: "Ахмад режет капусту." },
        { en: "Sara boils the rice in a pot.", ru: "Сара варит рис в кастрюле." },
        { en: "They fry the mushrooms in a pan.", ru: "Они жарят грибы на сковороде." },
        { en: '"Get the salt, please."', ru: "«Передай соль, пожалуйста.»" },
        { en: "They have dinner together.", ru: "Они ужинают вместе." },
        { en: "The food is hot and lovely.", ru: "Еда горячая и вкусная." },
        { en: '"I get tired at work."', ru: "«Я устаю на работе.»" },
        { en: '"I am happy here."', ru: "«Здесь я счастлив.»" },
        { en: "Ahmad has a cup of tea.", ru: "Ахмад пьёт чашку чая." },
        { en: '"This dinner is great!"', ru: "«Этот ужин отличный!»" },
      ],
      glossary: [
        { en: "first", transcr: "фёст", ru: "сначала, первый", pn: "/fɜːst/" },
        { en: "together", transcr: "тэгэзэ", ru: "вместе", pn: "/təˈɡeðə/" },
      ],
      quiz: [
        { q_ru: "Что готовят Ахмад и друзья?", opts_ru: ["Ужин", "Завтрак", "Чай", "Хлеб"], c: 0 },
        { q_ru: "Что делает Сара?", opts_ru: ["Чистит морковь", "Жарит грибы", "Варит рис", "Режет капусту"], c: 0 },
        { q_ru: "Какой получился ужин?", opts_ru: ["Горячий и вкусный", "Холодный", "Пустой", "Готовый утром"], c: 0 },
      ],
    },
    {
      id: 23,
      emoji: "🏦",
      title_ru: "Два сезона",
      title_en: "Two seasons",
      sentences: [
        { en: "It is the end of the second season.", ru: "Это конец второго сезона." },
        { en: "Ahmad has worked hard this year.", ru: "В этом году Ахмад усердно работал." },
        { en: "He has learned English.", ru: "Он выучил английский." },
        { en: "He has worked two seasons here.", ru: "Он отработал здесь два сезона." },
        { en: "He has just got his last payslip.", ru: "Он только что получил последнюю расчётку." },
        { en: "Ahmad has opened a bank account.", ru: "Ахмад открыл счёт в банке." },
        { en: '"Have you ever worked on a farm?" asks the new worker.', ru: "«Ты когда-нибудь работал на ферме?» — спрашивает новый рабочий." },
        { en: '"Yes, I have worked here. This is my second season."', ru: "«Да, я работал здесь. Это мой второй сезон.»" },
        { en: '"I have never been late."', ru: "«Я никогда не опаздывал.»" },
        { en: "He has already filled in the form.", ru: "Он уже заполнил форму." },
        { en: "Ahmad has got his wage.", ru: "Ахмад получил зарплату." },
        { en: "He has got money in the bank now.", ru: "Теперь у него есть деньги в банке." },
        { en: '"I have not packed the box yet."', ru: "«Я ещё не упаковал коробку.»" },
        { en: "Ahmad is proud of his work.", ru: "Ахмад гордится своей работой." },
        { en: '"I am going to work here next season!"', ru: "«В следующем сезоне я снова буду здесь работать!»" },
        { en: "It is a great end to the season.", ru: "Это отличный конец сезона." },
      ],
      glossary: [
        { en: "end", transcr: "энд", ru: "конец", pn: "/end/" },
        { en: "learn", transcr: "лён", ru: "учиться, выучить", pn: "/lɜːn/" },
        { en: "new", transcr: "нью", ru: "новый", pn: "/njuː/" },
        { en: "second", transcr: "сэкэнд", ru: "второй", pn: "/ˈsekənd/" },
      ],
      quiz: [
        { q_ru: "Сколько сезонов Ахмад отработал?", opts_ru: ["Два", "Один", "Три", "Пять"], c: 0 },
        { q_ru: "Что Ахмад открыл в банке?", opts_ru: ["Счёт", "Дверь", "Коробку", "Форму"], c: 0 },
        { q_ru: "Что чувствует Ахмад в конце?", opts_ru: ["Гордость за свою работу", "Скуку", "Страх", "Усталость"], c: 0 },
      ],
    },
  ];

  // Second book: a "fixed level" reader (book.gate = 15 unlocks ALL chapters at once,
  // after the A0-A1 course; book.level = 15 = vocabulary cap = union of lessons 1..15).
  // A parallel story about Fatima (a woman seasonal worker; "fatima" is in NAMES).
  // Chapter ids are unique WITHIN this book (1..N); read-tracking is book-scoped.
  const MADINA = [
    {
      id: 1,
      emoji: "🧳",
      title_ru: "Мадина приезжает",
      title_en: "Madina arrives",
      sentences: [
        { en: "Hello! I am Madina.", ru: "Привет! Я — Мадина." },
        { en: "I am from Tajikistan.", ru: "Я из Таджикистана." },
        { en: "I am a worker.", ru: "Я рабочая." },
        { en: "This is a big farm.", ru: "Это большая ферма." },
        { en: "Tom is the manager.", ru: "Том — менеджер." },
        { en: '"Good morning, Madina! Welcome!"', ru: "«Доброе утро, Мадина! Добро пожаловать!»" },
        { en: "Madina is a new picker.", ru: "Мадина — новая сборщица." },
        { en: "Anna is a packer.", ru: "Анна — упаковщица." },
        { en: "Anna is her friend now.", ru: "Теперь Анна — её подруга." },
        { en: "Madina looks at the big field.", ru: "Мадина смотрит на большое поле." },
        { en: "The work is new here.", ru: "Работа здесь новая." },
        { en: "Madina is happy.", ru: "Мадина рада." },
        { en: '"You are welcome, Madina!"', ru: "«Тебе здесь рады, Мадина!»" },
      ],
      glossary: [
        { en: "big", transcr: "биг", ru: "большой", pn: "/bɪɡ/" },
        { en: "new", transcr: "нью", ru: "новый", pn: "/njuː/" },
      ],
      quiz: [
        { q_ru: "Откуда приехала Мадина?", opts_ru: ["Из Таджикистана", "Из Британии", "Из Казахстана", "Из Узбекистана"], c: 0 },
        { q_ru: "Кто Мадина на ферме?", opts_ru: ["Сборщица", "Менеджер", "Водитель", "Повар"], c: 0 },
        { q_ru: "Кто стал её подругой?", opts_ru: ["Анна", "Том", "Джон", "Али"], c: 0 },
      ],
    },
    {
      id: 2,
      emoji: "👨‍👩‍👧",
      title_ru: "Семья Мадины",
      title_en: "Madina's family",
      sentences: [
        { en: "Madina has a family in Tajikistan.", ru: "У Мадины семья в Таджикистане." },
        { en: "Her mother is kind.", ru: "Её мама добрая." },
        { en: "Her father is a farmer.", ru: "Её папа — фермер." },
        { en: "Madina has one son and one daughter.", ru: "У Мадины один сын и одна дочь." },
        { en: "Her son is small.", ru: "Её сын маленький." },
        { en: "Madina works on the farm in Britain.", ru: "Мадина работает на ферме в Британии." },
        { en: "She sends money to her family.", ru: "Она отправляет деньги семье." },
        { en: '"I love my family!"', ru: "«Я люблю свою семью!»" },
        { en: "Madina talks to her mother on the phone.", ru: "Мадина говорит с мамой по телефону." },
        { en: '"Good morning, Mother!"', ru: "«Доброе утро, мама!»" },
        { en: "Her mother is happy.", ru: "Её мама рада." },
        { en: "Madina is a good mother.", ru: "Мадина — хорошая мать." },
      ],
      glossary: [
        { en: "kind", transcr: "кайнд", ru: "добрый", pn: "/kaɪnd/" },
        { en: "small", transcr: "смол", ru: "маленький", pn: "/smɔːl/" },
      ],
      quiz: [
        { q_ru: "Где семья Мадины?", opts_ru: ["В Таджикистане", "В Британии", "В Казахстане", "На ферме"], c: 0 },
        { q_ru: "Сколько детей у Мадины?", opts_ru: ["Сын и дочь", "Только сын", "Трое", "Нет детей"], c: 0 },
        { q_ru: "Как Мадина говорит с мамой?", opts_ru: ["По телефону", "Письмом", "Лично", "Никак"], c: 0 },
      ],
    },
    {
      id: 3,
      emoji: "🧺",
      title_ru: "Первый рабочий день",
      title_en: "The first work day",
      sentences: [
        { en: "Today is a work day.", ru: "Сегодня рабочий день." },
        { en: "Madina picks berries in the field.", ru: "Мадина собирает ягоды в поле." },
        { en: "She fills a punnet.", ru: "Она наполняет корзинку." },
        { en: "The punnet is full.", ru: "Корзинка полная." },
        { en: "Madina packs the boxes.", ru: "Мадина упаковывает коробки." },
        { en: "Anna helps her.", ru: "Анна ей помогает." },
        { en: '"You are fast, Madina!"', ru: "«Ты быстрая, Мадина!»" },
        { en: "Madina lifts the crate.", ru: "Мадина поднимает ящик." },
        { en: "The crate is heavy.", ru: "Ящик тяжёлый." },
        { en: "She works quickly.", ru: "Она работает быстро." },
        { en: "It is a long day.", ru: "Это долгий день." },
        { en: "Madina is tired.", ru: "Мадина устала." },
        { en: '"Good work, Madina!"', ru: "«Хорошая работа, Мадина!»" },
      ],
      glossary: [
        { en: "fast", transcr: "фаст", ru: "быстрый", pn: "/fɑːst/" },
        { en: "quickly", transcr: "куикли", ru: "быстро", pn: "/ˈkwɪkli/" },
        { en: "long", transcr: "лонг", ru: "долгий, длинный", pn: "/lɒŋ/" },
      ],
      quiz: [
        { q_ru: "Что собирает Мадина?", opts_ru: ["Ягоды", "Яблоки", "Картошку", "Цветы"], c: 0 },
        { q_ru: "Кто помогает Мадине?", opts_ru: ["Анна", "Том", "Мама", "Джон"], c: 0 },
        { q_ru: "Какой ящик?", opts_ru: ["Тяжёлый", "Пустой", "Маленький", "Сломанный"], c: 0 },
      ],
    },
    {
      id: 4,
      emoji: "🛏️",
      title_ru: "Комната Мадины",
      title_en: "Madina's room",
      sentences: [
        { en: "Madina has a room in the camp.", ru: "У Мадины комната в кэмпе." },
        { en: "There is a bed and a chair.", ru: "Там кровать и стул." },
        { en: "There is a small heater.", ru: "Там маленький обогреватель." },
        { en: "The room is cold.", ru: "В комнате холодно." },
        { en: "Madina turns on the heater.", ru: "Мадина включает обогреватель." },
        { en: "Now the room is warm.", ru: "Теперь в комнате тепло." },
        { en: "There is a kettle and a fridge.", ru: "Там чайник и холодильник." },
        { en: "Madina has tea.", ru: "Мадина пьёт чай." },
        { en: "The room is clean and tidy.", ru: "Комната чистая и опрятная." },
        { en: "Her bag is on the bed.", ru: "Её сумка на кровати." },
        { en: '"I want to rest."', ru: "«Я хочу отдохнуть.»" },
        { en: "The bed is warm.", ru: "Кровать тёплая." },
        { en: "Madina is happy in her room.", ru: "Мадина рада в своей комнате." },
      ],
      glossary: [
        { en: "small", transcr: "смол", ru: "маленький", pn: "/smɔːl/" },
        { en: "warm", transcr: "уорм", ru: "тёплый", pn: "/wɔːm/" },
        { en: "tidy", transcr: "тайди", ru: "опрятный, прибранный", pn: "/ˈtaɪdi/" },
      ],
      quiz: [
        { q_ru: "Что Мадина включает?", opts_ru: ["Обогреватель", "Свет", "Телефон", "Чайник"], c: 0 },
        { q_ru: "Какая комната после обогревателя?", opts_ru: ["Тёплая", "Холодная", "Грязная", "Пустая"], c: 0 },
        { q_ru: "Что хочет Мадина?", opts_ru: ["Отдохнуть", "Работать", "Готовить", "Гулять"], c: 0 },
      ],
    },
    {
      id: 5,
      emoji: "🛒",
      title_ru: "В магазине",
      title_en: "In the shop",
      sentences: [
        { en: "Madina is in the shop.", ru: "Мадина в магазине." },
        { en: "She has a shopping list.", ru: "У неё список покупок." },
        { en: "Madina buys bread and milk.", ru: "Мадина покупает хлеб и молоко." },
        { en: "She buys rice and eggs.", ru: "Она покупает рис и яйца." },
        { en: "The bread is fresh.", ru: "Хлеб свежий." },
        { en: "Madina looks at the price.", ru: "Мадина смотрит на цену." },
        { en: '"How much is the milk?"', ru: "«Сколько стоит молоко?»" },
        { en: '"It is one pound."', ru: "«Один фунт.»" },
        { en: "Madina gives the money.", ru: "Мадина отдаёт деньги." },
        { en: "The food is cheap.", ru: "Еда недорогая." },
        { en: "Madina takes the bag.", ru: "Мадина берёт сумку." },
        { en: "She walks to the camp.", ru: "Она идёт в кэмп." },
        { en: '"Thanks!"', ru: "«Спасибо!»" },
      ],
      glossary: [
        { en: "fresh", transcr: "фрэш", ru: "свежий", pn: "/freʃ/" },
        { en: "cheap", transcr: "чип", ru: "дешёвый, недорогой", pn: "/tʃiːp/" },
      ],
      quiz: [
        { q_ru: "Что покупает Мадина?", opts_ru: ["Хлеб и молоко", "Мясо и рыбу", "Чай и кофе", "Овощи"], c: 0 },
        { q_ru: "Какой хлеб?", opts_ru: ["Свежий", "Старый", "Дорогой", "Чёрствый"], c: 0 },
        { q_ru: "Сколько стоит молоко?", opts_ru: ["Один фунт", "Два фунта", "Пять фунтов", "Бесплатно"], c: 0 },
      ],
    },
    {
      id: 6,
      emoji: "🤝",
      title_ru: "Хороший день",
      title_en: "A good day",
      sentences: [
        { en: "It is Sunday.", ru: "Воскресенье." },
        { en: "Madina is free today.", ru: "Сегодня Мадина свободна." },
        { en: "Anna is her friend.", ru: "Анна — её подруга." },
        { en: "They walk together.", ru: "Они гуляют вместе." },
        { en: "Madina and Anna talk.", ru: "Мадина и Анна болтают." },
        { en: '"I like this farm."', ru: "«Мне нравится эта ферма.»" },
        { en: '"I like my friends."', ru: "«Мне нравятся мои друзья.»" },
        { en: "They have tea together.", ru: "Они пьют чай вместе." },
        { en: "The day is lovely.", ru: "День прекрасный." },
        { en: "Madina is happy here.", ru: "Мадина счастлива здесь." },
        { en: '"This is a good day!"', ru: "«Это хороший день!»" },
        { en: "Madina learns English.", ru: "Мадина учит английский." },
        { en: '"I am happy here!"', ru: "«Я счастлива здесь!»" },
      ],
      glossary: [
        { en: "together", transcr: "тэгэзэ", ru: "вместе", pn: "/təˈɡeðə/" },
        { en: "learn", transcr: "лён", ru: "учить, учиться", pn: "/lɜːn/" },
      ],
      quiz: [
        { q_ru: "Какой это день?", opts_ru: ["Воскресенье", "Понедельник", "Рабочий день", "Пятница"], c: 0 },
        { q_ru: "Что делают Мадина и Анна?", opts_ru: ["Гуляют и пьют чай", "Работают", "Спят", "Готовят"], c: 0 },
        { q_ru: "Что учит Мадина?", opts_ru: ["Английский", "Математику", "Ничего", "Русский"], c: 0 },
      ],
    },
    {
      id: 7, emoji: "🌧️", title_ru: "Дождливый день", title_en: "A rainy day",
      sentences: [
        { en: "It is Tuesday.", ru: "Сегодня вторник." },
        { en: "It is raining today.", ru: "Сегодня идёт дождь." },
        { en: "The sky is grey.", ru: "Небо серое." },
        { en: "Madina is walking to the field.", ru: "Мадина идёт в поле." },
        { en: "Her jacket is wet.", ru: "Её куртка мокрая." },
        { en: "She is carrying her bag quickly.", ru: "Она быстро несёт свою сумку." },
        { en: "Tom is standing near the gate.", ru: "Том стоит рядом с воротами." },
        { en: "He is talking to the team.", ru: "Он разговаривает с командой." },
        { en: "Anna is picking berries in the rain.", ru: "Анна собирает ягоды под дождём." },
        { en: "She is working quickly.", ru: "Она работает быстро." },
        { en: "Madina is filling the crate slowly.", ru: "Мадина наполняет ящик медленно." },
        { en: "John is helping Madina.", ru: "Джон помогает Мадине." },
        { en: '"What are you doing, Madina?"', ru: "«Что ты делаешь, Мадина?»" },
        { en: '"I am picking berries, Tom!"', ru: "«Я собираю ягоды, Том!»" },
        { en: "The rain stops at three o'clock.", ru: "Дождь прекращается в три часа." },
        { en: "Madina is happy.", ru: "Мадина рада." },
      ],
      glossary: [
        { en: "slowly", transcr: "слоули", ru: "медленно", pn: "/ˈsləʊli/" },
        { en: "quickly", transcr: "куикли", ru: "быстро", pn: "/ˈkwɪkli/" },
        { en: "sky", transcr: "скай", ru: "небо", pn: "/skaɪ/" },
      ],
      quiz: [
        { q_ru: "Что делает Мадина в начале истории?", opts_ru: ["Идёт в поле", "Стоит у ворот", "Пьёт чай", "Помогает Анне"], c: 0 },
        { q_ru: "Кто работает быстро?", opts_ru: ["Том", "Анна", "Джон", "Мадина"], c: 1 },
        { q_ru: "Когда прекращается дождь?", opts_ru: ["В три часа", "В семь часов", "Утром", "В пятницу"], c: 0 },
      ],
    },
    {
      id: 8, emoji: "🦺", title_ru: "Одежда и безопасность", title_en: "Clothes and safety",
      sentences: [
        { en: "It is a work day.", ru: "Сегодня рабочий день." },
        { en: "Madina has a yellow vest.", ru: "У Мадины жёлтый жилет." },
        { en: "She has green wellies.", ru: "У неё зелёные резиновые сапоги." },
        { en: "She has orange gloves.", ru: "У неё оранжевые перчатки." },
        { en: "Her jacket is blue.", ru: "Её куртка синяя." },
        { en: "Her jacket is warm.", ru: "Её куртка тёплая." },
        { en: "Madina has a helmet.", ru: "У Мадины каска." },
        { en: "The helmet is safe.", ru: "Каска защищает." },
        { en: "She has goggles.", ru: "У неё защитные очки." },
        { en: "Tom has a white cap.", ru: "У Тома белая кепка." },
        { en: "Anna has a red coat.", ru: "У Анны красное пальто." },
        { en: '"Do you have your mask, Madina?"', ru: "«У тебя есть маска, Мадина?»" },
        { en: '"Yes! I have my mask."', ru: "«Да! У меня есть маска.»" },
        { en: "Madina is a safe worker.", ru: "Мадина — аккуратный работник." },
      ],
      glossary: [
        { en: "warm", transcr: "уорм", ru: "тёплый", pn: "/wɔːm/" },
        { en: "safe", transcr: "сэйф", ru: "безопасный, защищает", pn: "/seɪf/" },
      ],
      quiz: [
        { q_ru: "Какого цвета жилет Мадины?", opts_ru: ["Жёлтый", "Красный", "Синий", "Белый"], c: 0 },
        { q_ru: "Что защищает голову Мадины?", opts_ru: ["Кепка (cap)", "Каска (helmet)", "Очки (goggles)", "Маска (mask)"], c: 1 },
        { q_ru: "Какая куртка у Мадины?", opts_ru: ["Красная и тёплая", "Белая и холодная", "Синяя и тёплая", "Жёлтая и новая"], c: 2 },
      ],
    },
    {
      id: 9, emoji: "📅", title_ru: "Вчерашняя смена", title_en: "Yesterday's shift",
      sentences: [
        { en: "Yesterday was Monday.", ru: "Вчера был понедельник." },
        { en: "Madina started work early.", ru: "Мадина начала работу рано." },
        { en: "She picked berries in the field.", ru: "Она собирала ягоды в поле." },
        { en: "Then she packed the boxes.", ru: "Потом она упаковала коробки." },
        { en: "She stacked the crates.", ru: "Она складывала ящики." },
        { en: "Anna helped Madina.", ru: "Анна помогала Мадине." },
        { en: "Tom checked the crates.", ru: "Том проверял ящики." },
        { en: "Madina ate lunch in the canteen.", ru: "Мадина обедала в столовой." },
        { en: "She drank some tea.", ru: "Она выпила чая." },
        { en: "She bought some bread.", ru: "Она купила хлеба." },
        { en: "Then she finished late.", ru: "Потом она закончила поздно." },
        { en: "She left the field at six o'clock.", ru: "Она ушла с поля в шесть часов." },
        { en: '"Good work, Madina!"', ru: "«Хорошая работа, Мадина!»" },
        { en: "It was a hard shift.", ru: "Это была тяжёлая смена." },
      ],
      glossary: [
        { en: "then", transcr: "зэн", ru: "потом, затем", pn: "/ðen/" },
      ],
      quiz: [
        { q_ru: "Что Мадина делала вчера?", opts_ru: ["Собирала ягоды и упаковывала коробки", "Водила трактор", "Чинила обогреватель", "Отдыхала"], c: 0 },
        { q_ru: "Что Мадина пила в столовой?", opts_ru: ["Чай", "Молоко", "Кофе", "Сок"], c: 0 },
        { q_ru: "Какой была смена?", opts_ru: ["Тяжёлой (hard)", "Лёгкой", "Короткой", "Скучной"], c: 0 },
      ],
    },
    {
      id: 10, emoji: "🩺", title_ru: "У врача", title_en: "At the doctor",
      sentences: [
        { en: "Madina is ill today.", ru: "Сегодня Мадина больна." },
        { en: "She has a pain in her arm.", ru: "У неё боль в руке." },
        { en: "Her arm hurts.", ru: "Рука болит." },
        { en: "She cannot pick berries.", ru: "Она не может собирать ягоды." },
        { en: "She cannot lift the crate.", ru: "Она не может поднять ящик." },
        { en: "Madina has an appointment.", ru: "У Мадины запись к врачу." },
        { en: "She is at the doctor.", ru: "Она у врача." },
        { en: "The nurse helps her.", ru: "Медсестра помогает ей." },
        { en: "The doctor is kind.", ru: "Врач добрый." },
        { en: '"Can you move your arm?"', ru: "«Можете подвигать рукой?»" },
        { en: '"I can move it."', ru: "«Я могу.»" },
        { en: "The doctor checks her arm.", ru: "Врач осматривает её руку." },
        { en: '"You can rest today."', ru: "«Сегодня можете отдыхать.»" },
        { en: "The nurse gives her medicine.", ru: "Медсестра даёт ей лекарство." },
        { en: "The next day, Madina is better.", ru: "На следующий день Мадине лучше." },
        { en: "She can work again.", ru: "Она снова может работать." },
      ],
      glossary: [
        { en: "kind", transcr: "кайнд", ru: "добрый", pn: "/kaɪnd/" },
        { en: "again", transcr: "эгэн", ru: "снова, опять", pn: "/əˈɡen/" },
      ],
      quiz: [
        { q_ru: "Что болит у Мадины?", opts_ru: ["Рука (arm)", "Нога (leg)", "Зуб (tooth)", "Голова (head)"], c: 0 },
        { q_ru: "Кто помогает Мадине у врача?", opts_ru: ["Медсестра (nurse)", "Анна", "Том", "Джон"], c: 0 },
        { q_ru: "Что Мадина может делать на следующий день?", opts_ru: ["Снова работать", "Водить трактор", "Нести ящики", "Бежать"], c: 0 },
      ],
    },
    {
      id: 11, emoji: "📋", title_ru: "В офисе", title_en: "In the office",
      sentences: [
        { en: "It is October.", ru: "Сейчас октябрь." },
        { en: "Madina is in the office.", ru: "Мадина в офисе." },
        { en: "First, Tom has a form.", ru: "Сначала у Тома анкета." },
        { en: '"What is your name?"', ru: "«Как ваше имя?»" },
        { en: '"My name is Madina."', ru: "«Меня зовут Мадина.»" },
        { en: '"What is your address?"', ru: "«Какой у вас адрес?»" },
        { en: "Madina gives her address.", ru: "Мадина называет свой адрес." },
        { en: "She gives her phone number.", ru: "Она называет свой номер телефона." },
        { en: '"When is your birthday?"', ru: "«Когда у вас день рождения?»" },
        { en: '"I was born in April."', ru: "«Я родилась в апреле.»" },
        { en: "Madina signs the contract.", ru: "Мадина подписывает контракт." },
        { en: '"This is a good contract."', ru: "«Это хороший контракт.»" },
        { en: "Madina fills in the form.", ru: "Мадина заполняет анкету." },
        { en: "Tom checks the form.", ru: "Том проверяет анкету." },
        { en: '"Thank you, Madina!"', ru: "«Спасибо, Мадина!»" },
      ],
      glossary: [
        { en: "first", transcr: "фёст", ru: "сначала, первый", pn: "/fɜːst/" },
      ],
      quiz: [
        { q_ru: "Где Мадина в этой главе?", opts_ru: ["В офисе", "В поле", "В магазине", "У врача"], c: 0 },
        { q_ru: "Когда день рождения Мадины?", opts_ru: ["В апреле", "В мае", "В октябре", "В декабре"], c: 0 },
        { q_ru: "Что Мадина подписывает?", opts_ru: ["Контракт (contract)", "Список (list)", "Билет (ticket)", "Анкету (form)"], c: 0 },
      ],
    },
    {
      id: 12, emoji: "🎉", title_ru: "Конец сезона", title_en: "End of the season",
      sentences: [
        { en: "It is the last day.", ru: "Это последний день." },
        { en: "The work is finished.", ru: "Работа закончена." },
        { en: "Madina is free today.", ru: "Сегодня Мадина свободна." },
        { en: "She is happy.", ru: "Она счастлива." },
        { en: "All her friends are here.", ru: "Все её друзья здесь." },
        { en: "They have a party.", ru: "У них вечеринка." },
        { en: "Anna is here.", ru: "Анна здесь." },
        { en: "Ahmad is here.", ru: "Ахмад здесь." },
        { en: "Sara cooks food.", ru: "Сара готовит еду." },
        { en: "The food is lovely.", ru: "Еда прекрасная." },
        { en: '"I love this farm!"', ru: "«Я люблю эту ферму!»" },
        { en: '"I love my friends!"', ru: "«Я люблю своих друзей!»" },
        { en: '"Goodbye, Anna! Goodbye, Tom!"', ru: "«До свидания, Анна! До свидания, Том!»" },
        { en: '"It is not the end!"', ru: "«Это не конец!»" },
        { en: "It is a great day.", ru: "Это отличный день." },
        { en: "Madina is happy here.", ru: "Мадина счастлива здесь." },
      ],
      glossary: [
        { en: "end", transcr: "энд", ru: "конец", pn: "/end/" },
        { en: "all", transcr: "ол", ru: "все, всё", pn: "/ɔːl/" },
      ],
      quiz: [
        { q_ru: "Какой это день?", opts_ru: ["Последний день сезона", "Первый день", "Обычная смена", "Выходной в середине"], c: 0 },
        { q_ru: "Кто готовит еду на вечеринке?", opts_ru: ["Сара", "Мадина", "Анна", "Том"], c: 0 },
        { q_ru: "Что чувствует Мадина в конце?", opts_ru: ["Она счастлива", "Она устала", "Она больна", "Ей холодно"], c: 0 },
      ],
    },
  ];

  // Third book: "История Бобура" — a fixed-level A1 REVIEW reader. Bobur is a new
  // male worker (in NAMES) on Ahmad's farm; simple stories recycle A0-A1 vocab.
  const BOBUR = [
    {
      id: 1, emoji: "✈️", title_ru: "Бобур приезжает", title_en: "Bobur arrives",
      sentences: [
        { en: "Hello! I am Bobur.", ru: "Привет! Я — Бобур." },
        { en: "I am from Uzbekistan.", ru: "Я из Узбекистана." },
        { en: "I am a new worker.", ru: "Я новый рабочий." },
        { en: "This is Britain.", ru: "Это Британия." },
        { en: "This is a big farm.", ru: "Это большая ферма." },
        { en: "Tom is the manager.", ru: "Том — менеджер." },
        { en: "He is British.", ru: "Он британец." },
        { en: '"Good morning, Bobur! Welcome!"', ru: "«Доброе утро, Бобур! Добро пожаловать!»" },
        { en: "Ahmad is here.", ru: "Ахмад здесь." },
        { en: "He is a picker.", ru: "Он сборщик." },
        { en: '"Hello, Bobur! I am Ahmad."', ru: "«Привет, Бобур! Я — Ахмад.»" },
        { en: "Ahmad is a good worker.", ru: "Ахмад — хороший работник." },
        { en: "Bobur is happy.", ru: "Бобур рад." },
        { en: '"You are welcome here, Bobur!"', ru: "«Тебе здесь рады, Бобур!»" },
      ],
      glossary: [
        { en: "big", transcr: "биг", ru: "большой", pn: "/bɪɡ/" },
      ],
      quiz: [
        { q_ru: "Откуда приехал Бобур?", opts_ru: ["Из Узбекистана", "Из Британии", "Из Казахстана", "Из Таджикистана"], c: 0 },
        { q_ru: "Кто из рабочих знакомится с Бобуром и помогает ему?", opts_ru: ["Ахмад", "Сара", "Джон", "Анна"], c: 0 },
        { q_ru: "Кем работает Бобур?", opts_ru: ["Сборщик (picker)", "Механик", "Менеджер", "Водитель"], c: 0 },
      ],
    },
    {
      id: 2, emoji: "🧰", title_ru: "Рабочий день", title_en: "A work day",
      sentences: [
        { en: "It is Monday.", ru: "Сегодня понедельник." },
        { en: "It is morning.", ru: "Сейчас утро." },
        { en: "Bobur is a picker.", ru: "Бобур — сборщик." },
        { en: "Ahmad is a picker.", ru: "Ахмад — сборщик." },
        { en: "They are in the field.", ru: "Они в поле." },
        { en: "Bobur is picking berries.", ru: "Бобур собирает ягоды." },
        { en: "He is filling the punnet.", ru: "Он наполняет корзинку." },
        { en: "The punnet is full.", ru: "Корзинка полная." },
        { en: "Ahmad is carrying the crate.", ru: "Ахмад несёт ящик." },
        { en: "The crate is heavy.", ru: "Ящик тяжёлый." },
        { en: '"Good work, Bobur!"', ru: "«Хорошая работа, Бобур!»" },
        { en: "It is a long day.", ru: "Это долгий день." },
        { en: "Bobur is tired.", ru: "Бобур устал." },
        { en: '"I like this job!"', ru: "«Мне нравится эта работа!»" },
      ],
      glossary: [
        { en: "long", transcr: "лонг", ru: "долгий, длинный", pn: "/lɒŋ/" },
      ],
      quiz: [
        { q_ru: "Что собирает Бобур?", opts_ru: ["Ягоды (berries)", "Картошку", "Яблоки", "Рыбу"], c: 0 },
        { q_ru: "Какой ящик несёт Ахмад?", opts_ru: ["Тяжёлый", "Пустой", "Маленький", "Сломанный"], c: 0 },
        { q_ru: "Какой это день?", opts_ru: ["Долгий", "Короткий", "Выходной", "Холодный"], c: 0 },
      ],
    },
    {
      id: 3, emoji: "🛏️", title_ru: "Комната Бобура", title_en: "Bobur's room",
      sentences: [
        { en: "This is Bobur's room.", ru: "Это комната Бобура." },
        { en: "The room is small.", ru: "Комната маленькая." },
        { en: "There is a bed.", ru: "Есть кровать." },
        { en: "There is a heater.", ru: "Есть обогреватель." },
        { en: "The heater is warm.", ru: "Обогреватель тёплый." },
        { en: "There is a blanket.", ru: "Есть одеяло." },
        { en: "The blanket is clean.", ru: "Одеяло чистое." },
        { en: "There is a shelf.", ru: "Есть полка." },
        { en: "Bobur's key is on the shelf.", ru: "Ключ Бобура на полке." },
        { en: "The room is tidy.", ru: "Комната опрятная." },
        { en: '"My room is good!"', ru: "«Моя комната хорошая!»" },
        { en: "Ahmad's room is near.", ru: "Комната Ахмада рядом." },
        { en: "They are good neighbours.", ru: "Они хорошие соседи." },
      ],
      glossary: [
        { en: "small", transcr: "смол", ru: "маленький", pn: "/smɔːl/" },
        { en: "warm", transcr: "уорм", ru: "тёплый", pn: "/wɔːm/" },
        { en: "tidy", transcr: "тайди", ru: "опрятный, прибранный", pn: "/ˈtaɪdi/" },
      ],
      quiz: [
        { q_ru: "Какая комната у Бобура?", opts_ru: ["Маленькая и опрятная", "Большая и грязная", "Холодная и пустая", "Тёмная"], c: 0 },
        { q_ru: "Что лежит на полке?", opts_ru: ["Ключ Бобура (key)", "Одеяло (blanket)", "Кружка", "Телефон"], c: 0 },
        { q_ru: "Кто сосед Бобура?", opts_ru: ["Ахмад", "Том", "Джон", "Сара"], c: 0 },
      ],
    },
    {
      id: 4, emoji: "🛒", title_ru: "В магазине", title_en: "At the shop",
      sentences: [
        { en: "It is Saturday.", ru: "Сегодня суббота." },
        { en: "Bobur is in the shop.", ru: "Бобур в магазине." },
        { en: "He has a shopping list.", ru: "У него список покупок." },
        { en: "He takes some bread.", ru: "Он берёт хлеб." },
        { en: "He takes some milk.", ru: "Он берёт молоко." },
        { en: "He takes some rice.", ru: "Он берёт рис." },
        { en: "The bread is fresh.", ru: "Хлеб свежий." },
        { en: '"How much is the milk?"', ru: "«Сколько стоит молоко?»" },
        { en: "The milk is one pound.", ru: "Молоко стоит один фунт." },
        { en: '"How much is the bread?"', ru: "«Сколько стоит хлеб?»" },
        { en: "The bread is cheap.", ru: "Хлеб дешёвый." },
        { en: "Bobur has cash.", ru: "У Бобура есть наличные." },
        { en: "He pays.", ru: "Он платит." },
        { en: "Bobur is happy.", ru: "Бобур рад." },
      ],
      glossary: [
        { en: "fresh", transcr: "фрэш", ru: "свежий", pn: "/freʃ/" },
        { en: "cheap", transcr: "чип", ru: "дешёвый", pn: "/tʃiːp/" },
      ],
      quiz: [
        { q_ru: "Что берёт Бобур в магазине?", opts_ru: ["Хлеб, молоко и рис", "Мясо и рыбу", "Чай и кофе", "Яйца и лук"], c: 0 },
        { q_ru: "Какой хлеб?", opts_ru: ["Свежий", "Старый", "Дорогой", "Чёрствый"], c: 0 },
        { q_ru: "Сколько стоит молоко?", opts_ru: ["Один фунт", "Два фунта", "Пять фунтов", "Бесплатно"], c: 0 },
      ],
    },
    {
      id: 5, emoji: "🤝", title_ru: "Новые друзья", title_en: "New friends",
      sentences: [
        { en: "Bobur is on the farm.", ru: "Бобур на ферме." },
        { en: "He has new friends.", ru: "У него новые друзья." },
        { en: "Ahmad is his friend.", ru: "Ахмад — его друг." },
        { en: "Anna is his colleague.", ru: "Анна — его коллега." },
        { en: "She is a packer.", ru: "Она упаковщица." },
        { en: "Sara is a cleaner.", ru: "Сара — уборщица." },
        { en: "John is a mechanic.", ru: "Джон — механик." },
        { en: "They are a team.", ru: "Они одна команда." },
        { en: '"I like football!"', ru: "«Я люблю футбол!»" },
        { en: '"I love music!"', ru: "«Я люблю музыку!»" },
        { en: '"I like this farm!"', ru: "«Мне нравится эта ферма!»" },
        { en: "They are together.", ru: "Они вместе." },
        { en: "Bobur is happy here.", ru: "Бобур счастлив здесь." },
      ],
      glossary: [
        { en: "together", transcr: "тэгэзэ", ru: "вместе", pn: "/təˈɡeðə/" },
      ],
      quiz: [
        { q_ru: "Кем работает Анна?", opts_ru: ["Упаковщица (packer)", "Уборщица", "Механик", "Менеджер"], c: 0 },
        { q_ru: "Что любит Бобур?", opts_ru: ["Футбол и музыку", "Дождь и холод", "Тяжёлую работу", "Тишину"], c: 0 },
        { q_ru: "Как Бобур чувствует себя на ферме?", opts_ru: ["Счастлив", "Грустит", "Устал", "Болеет"], c: 0 },
      ],
    },
    {
      id: 6, emoji: "📱", title_ru: "Письмо домой", title_en: "A letter home",
      sentences: [
        { en: "It is Sunday.", ru: "Сегодня воскресенье." },
        { en: "Bobur is in his room.", ru: "Бобур в своей комнате." },
        { en: "He has his phone.", ru: "У него телефон." },
        { en: "He is sending a photo.", ru: "Он отправляет фото." },
        { en: "Ahmad is helping Bobur.", ru: "Ахмад помогает Бобуру." },
        { en: '"I am a picker."', ru: "«Я сборщик.»" },
        { en: '"I am working on a farm in Britain."', ru: "«Я работаю на ферме в Британии.»" },
        { en: '"The farm is big."', ru: "«Ферма большая.»" },
        { en: '"My friends are kind."', ru: "«Мои друзья добрые.»" },
        { en: '"I am happy here."', ru: "«Я счастлив здесь.»" },
        { en: '"I love this work!"', ru: "«Я люблю эту работу!»" },
        { en: "Bobur is a good worker.", ru: "Бобур — хороший работник." },
        { en: "Ahmad is a good friend.", ru: "Ахмад — хороший друг." },
        { en: '"Thank you, Ahmad!"', ru: "«Спасибо, Ахмад!»" },
      ],
      glossary: [
        { en: "big", transcr: "биг", ru: "большой", pn: "/bɪɡ/" },
        { en: "kind", transcr: "кайнд", ru: "добрый", pn: "/kaɪnd/" },
      ],
      quiz: [
        { q_ru: "Что Бобур отправляет домой?", opts_ru: ["Фото", "Деньги", "Ящик", "Письмо на бумаге"], c: 0 },
        { q_ru: "Кто помогает Бобуру с телефоном?", opts_ru: ["Ахмад", "Том", "Сара", "Джон"], c: 0 },
        { q_ru: "Что Бобур говорит о друзьях?", opts_ru: ["Они добрые", "Они далеко", "Они устали", "Они новые"], c: 0 },
      ],
    },
  ];

  // Fourth book: "Ахмад — третий сезон" — a fixed-level A2 reader (gate/level = 23).
  // Ahmad returns for a third season; uses A2 grammar (going to, comparatives,
  // could, have got, compounds, infinitive of purpose, Present Perfect).
  const AHMAD3 = [
    {
      id: 1, emoji: "🌿", title_ru: "Третий сезон", title_en: "The third season",
      sentences: [
        { en: "Ahmad is here again.", ru: "Ахмад снова здесь." },
        { en: "This is his third season on the farm.", ru: "Это его третий сезон на ферме." },
        { en: "He is not nervous now.", ru: "Теперь он не волнуется." },
        { en: "He is talking to everyone.", ru: "Он разговаривает со всеми." },
        { en: "Tom is the manager again.", ru: "Том снова менеджер." },
        { en: '"Hello, Ahmad! Welcome back!"', ru: "«Привет, Ахмад! С возвращением!»" },
        { en: "Ahmad has worked two seasons here.", ru: "Ахмад отработал здесь два сезона." },
        { en: "He has learned English.", ru: "Он выучил английский." },
        { en: "He is going to work in the warehouse this season.", ru: "В этом сезоне он будет работать на складе." },
        { en: "Everyone is glad now.", ru: "Теперь все рады." },
        { en: "Anna is here again.", ru: "Анна снова здесь." },
        { en: '"It is good to be back!"', ru: "«Как хорошо вернуться!»" },
        { en: "Ahmad is calm now.", ru: "Теперь Ахмад спокоен." },
        { en: "He is ready to work hard.", ru: "Он готов усердно работать." },
      ],
      glossary: [
        { en: "third", transcr: "сёд", ru: "третий", pn: "/θɜːd/" },
        { en: "learn", transcr: "лён", ru: "учиться, выучить", pn: "/lɜːn/" },
        { en: "again", transcr: "эгэн", ru: "снова, опять", pn: "/əˈɡen/" },
      ],
      quiz: [
        { q_ru: "Какой это сезон для Ахмада на ферме?", opts_ru: ["Третий", "Первый", "Второй", "Последний"], c: 0 },
        { q_ru: "Где Ахмад будет работать в этом сезоне?", opts_ru: ["На складе (warehouse)", "В поле", "В офисе", "В столовой"], c: 0 },
        { q_ru: "Как Ахмад себя чувствует в начале сезона?", opts_ru: ["Спокойно и уверенно", "Нервно", "Грустно", "Плохо"], c: 0 },
      ],
    },
    {
      id: 2, emoji: "📦", title_ru: "Склад", title_en: "The warehouse",
      sentences: [
        { en: "Today Ahmad is working in the warehouse.", ru: "Сегодня Ахмад работает на складе." },
        { en: "The warehouse is big.", ru: "Склад большой." },
        { en: "It is full of crates and pallets.", ru: "Он полон ящиков и поддонов." },
        { en: "Ahmad is stronger than last season.", ru: "Ахмад сильнее, чем в прошлом сезоне." },
        { en: "He can carry heavy crates easily.", ru: "Он может легко носить тяжёлые ящики." },
        { en: "A full crate is heavier than an empty crate.", ru: "Полный ящик тяжелее пустого." },
        { en: "Ahmad lifts the heavy crate.", ru: "Ахмад поднимает тяжёлый ящик." },
        { en: '"Where is this crate going?"', ru: "«Куда идёт этот ящик?»" },
        { en: '"It is going to the lorry."', ru: "«Он едет на грузовик.»" },
        { en: "Ahmad is packing the boxes carefully.", ru: "Ахмад аккуратно упаковывает коробки." },
        { en: "His work is better than last season.", ru: "Его работа лучше, чем в прошлом сезоне." },
        { en: "Tom is checking the boxes.", ru: "Том проверяет коробки." },
        { en: '"You are the best worker here, Ahmad!"', ru: "«Ты лучший работник здесь, Ахмад!»" },
        { en: "Ahmad is proud of his work.", ru: "Ахмад гордится своей работой." },
      ],
      glossary: [
        { en: "big", transcr: "биг", ru: "большой", pn: "/bɪɡ/" },
      ],
      quiz: [
        { q_ru: "Где работает Ахмад в этой главе?", opts_ru: ["На складе (warehouse)", "В поле", "В офисе", "На кухне"], c: 0 },
        { q_ru: "Что тяжелее?", opts_ru: ["Полный ящик", "Пустой ящик", "Перчатки", "Поддон"], c: 0 },
        { q_ru: "Как Ахмад работает в этом сезоне?", opts_ru: ["Лучше, чем в прошлом", "Хуже", "Так же", "Медленнее"], c: 0 },
      ],
    },
    {
      id: 3, emoji: "💰", title_ru: "Зарплата", title_en: "Wages",
      sentences: [
        { en: "It is Friday.", ru: "Сегодня пятница." },
        { en: "Ahmad has got his payslip.", ru: "Ахмад получил расчётный лист." },
        { en: "His pay is good this season.", ru: "Его зарплата хорошая в этом сезоне." },
        { en: "He has worked overtime this season.", ru: "В этом сезоне он работал сверхурочно." },
        { en: "His wage is higher than last year.", ru: "Его зарплата выше, чем в прошлом году." },
        { en: "Ahmad has a bank account.", ru: "У Ахмада есть банковский счёт." },
        { en: "He is going to the bank to transfer money.", ru: "Он идёт в банк, чтобы перевести деньги." },
        { en: "He is going to transfer money abroad.", ru: "Он собирается перевести деньги за границу." },
        { en: '"How much is the transfer fee?"', ru: "«Сколько стоит перевод?»" },
        { en: '"The fee is five pounds."', ru: "«Комиссия — пять фунтов.»" },
        { en: "Ahmad checks the balance on his statement.", ru: "Ахмад проверяет баланс в выписке." },
        { en: "He has money in the bank now.", ru: "Теперь у него есть деньги в банке." },
        { en: "Ahmad is glad. His pay is good.", ru: "Ахмад рад. Его зарплата хорошая." },
        { en: "He is going to save more money this season.", ru: "В этом сезоне он собирается откладывать больше." },
      ],
      glossary: [
        { en: "abroad", transcr: "эброд", ru: "за границу, за границей", pn: "/əˈbrɔːd/" },
      ],
      quiz: [
        { q_ru: "Зачем Ахмад идёт в банк?", opts_ru: ["Перевести деньги за границу", "Купить хлеб", "Встретить друга", "Снять паспорт"], c: 0 },
        { q_ru: "Какая зарплата у Ахмада в этом сезоне?", opts_ru: ["Выше, чем в прошлом году", "Ниже, чем в прошлом году", "Такая же", "Нулевая"], c: 0 },
        { q_ru: "Что Ахмад планирует делать с деньгами?", opts_ru: ["Откладывать больше", "Тратить всё", "Потерять", "Отдать менеджеру"], c: 0 },
      ],
    },
    {
      id: 4, emoji: "🌦️", title_ru: "Прогноз погоды", title_en: "The forecast",
      sentences: [
        { en: "It is autumn.", ru: "Сейчас осень." },
        { en: "Ahmad is looking at the weather forecast.", ru: "Ахмад смотрит прогноз погоды." },
        { en: "It is going to be cold tomorrow.", ru: "Завтра будет холодно." },
        { en: "It is going to be colder than today.", ru: "Будет холоднее, чем сегодня." },
        { en: "Tomorrow there is fog and strong wind.", ru: "Завтра туман и сильный ветер." },
        { en: '"It is going to be a difficult day."', ru: "«Будет тяжёлый день.»" },
        { en: "Ahmad is going to take his warm jacket.", ru: "Ахмад возьмёт тёплую куртку." },
        { en: "He is going to take his waterproof coat.", ru: "Он возьмёт непромокаемое пальто." },
        { en: "Winter is colder than autumn.", ru: "Зима холоднее осени." },
        { en: "Summer is the best picking season.", ru: "Лето — лучший сезон для сбора урожая." },
        { en: '"What is the weather going to be on Friday?"', ru: "«Какая погода будет в пятницу?»" },
        { en: '"It is going to be sunny and warm."', ru: "«Будет солнечно и тепло.»" },
        { en: "Ahmad is glad it is going to be warm soon.", ru: "Ахмад рад, что скоро потеплеет." },
        { en: "Now Ahmad is ready to work.", ru: "Теперь Ахмад готов работать." },
      ],
      glossary: [
        { en: "waterproof", transcr: "уотэпруф", ru: "непромокаемый", pn: "/ˈwɔːtəpruːf/" },
      ],
      quiz: [
        { q_ru: "Какая погода будет завтра по прогнозу?", opts_ru: ["Холодно, туман и ветер", "Солнечно и жарко", "Снег весь день", "Тепло и сухо"], c: 0 },
        { q_ru: "Какой сезон лучший для сбора урожая?", opts_ru: ["Лето", "Зима", "Осень", "Весна"], c: 0 },
        { q_ru: "Что Ахмад собирается взять в холодный день?", opts_ru: ["Тёплую куртку и непромокаемое пальто", "Шорты и футболку", "Только перчатки", "Зонт"], c: 0 },
      ],
    },
    {
      id: 5, emoji: "🏥", title_ru: "Помощь новому рабочему", title_en: "Helping a new worker",
      sentences: [
        { en: "There is a new worker at the farm.", ru: "На ферме новый рабочий." },
        { en: "His name is Omar.", ru: "Его зовут Омар." },
        { en: "Omar is nervous.", ru: "Омар нервничает." },
        { en: "Ahmad is going to help him.", ru: "Ахмад собирается ему помочь." },
        { en: '"I have worked here. Everything is fine."', ru: "«Я работал здесь. Всё в порядке.»" },
        { en: "Omar has got something in his eye.", ru: "У Омара что-то попало в глаз." },
        { en: '"Does it hurt?"', ru: "«Болит?»" },
        { en: '"Yes, it is sore."', ru: "«Да, болит.»" },
        { en: "Ahmad is going to take him to the pharmacy.", ru: "Ахмад собирается отвести его в аптеку." },
        { en: '"The pharmacy is in town."', ru: "«Аптека в городе.»" },
        { en: '"You can go to the doctor here."', ru: "«Здесь можно пойти к врачу.»" },
        { en: '"It is free. You do not pay."', ru: "«Это бесплатно. Платить не надо.»" },
        { en: '"You can get an appointment at the clinic."', ru: "«Можно записаться на приём в клинику.»" },
        { en: "Now Omar is calm.", ru: "Теперь Омар спокоен." },
        { en: '"Thank you, Ahmad! You are a good friend."', ru: "«Спасибо, Ахмад! Ты хороший друг.»" },
      ],
      glossary: [],
      quiz: [
        { q_ru: "Как чувствует себя Омар в начале?", opts_ru: ["Он нервничает", "Он счастлив", "Он устал", "Он зол"], c: 0 },
        { q_ru: "Куда Ахмад собирается отвести Омара?", opts_ru: ["В аптеку (pharmacy)", "В банк", "В офис", "На ферму"], c: 0 },
        { q_ru: "Что Ахмад говорит Омару о враче?", opts_ru: ["Врач здесь бесплатный", "Нужно платить много", "Врача нет в городе", "Клиника закрыта"], c: 0 },
      ],
    },
    {
      id: 6, emoji: "🏡", title_ru: "Последний день", title_en: "The last day",
      sentences: [
        { en: "It is the last day of season three.", ru: "Это последний день третьего сезона." },
        { en: "Ahmad has worked hard this season.", ru: "Ахмад усердно работал в этом сезоне." },
        { en: "He has never been late.", ru: "Он никогда не опаздывал." },
        { en: "He has helped everyone on the team.", ru: "Он помогал всем в команде." },
        { en: "Tom gives Ahmad a letter.", ru: "Том даёт Ахмаду письмо." },
        { en: '"You have been the best worker this season."', ru: "«Ты был лучшим работником в этом сезоне.»" },
        { en: "Ahmad is proud.", ru: "Ахмад гордится." },
        { en: "He has already packed his bag.", ru: "Он уже собрал сумку." },
        { en: "Everyone is standing at the gate.", ru: "Все стоят у ворот." },
        { en: '"We are going to miss you, Ahmad!"', ru: "«Мы будем скучать по тебе, Ахмад!»" },
        { en: "Ahmad has money in the bank now.", ru: "Теперь у Ахмада есть деньги в банке." },
        { en: "He is going to his family.", ru: "Он едет к семье." },
        { en: '"I am going to work here next season!"', ru: "«В следующем сезоне я снова буду здесь работать!»" },
        { en: "Ahmad is happy and proud.", ru: "Ахмад счастлив и горд." },
      ],
      glossary: [
        { en: "miss", transcr: "мис", ru: "скучать", pn: "/mɪs/" },
      ],
      quiz: [
        { q_ru: "Что Том говорит Ахмаду в конце сезона?", opts_ru: ["Ты был лучшим работником", "Ты опоздал сегодня", "Иди на склад", "Возьми новый ящик"], c: 0 },
        { q_ru: "Что Ахмад уже сделал перед отъездом?", opts_ru: ["Собрал сумку", "Купил билет на поезд", "Позвонил врачу", "Потерял деньги"], c: 0 },
        { q_ru: "Что Ахмад обещает в конце?", opts_ru: ["Вернуться в следующем сезоне", "Никогда не возвращаться", "Остаться на зиму", "Уйти с фермы"], c: 0 },
      ],
    },
  ];

  // Fifth book: "Выживание на ферме" — a fixed-level A1 survival reader (gate/level
  // = 15): health/NHS, money/bank, documents. High-responsibility domain — neutral
  // lines only, no medical/legal/visa/earnings claims.
  const SURVIVAL = [
    {
      id: 1, emoji: "🤒", title_ru: "Я болен", title_en: "I am ill",
      sentences: [
        { en: "Ahmad is ill today.", ru: "Сегодня Ахмад болен." },
        { en: "He is in his room.", ru: "Он в своей комнате." },
        { en: "Ahmad has a headache.", ru: "У Ахмада болит голова." },
        { en: "He has a fever.", ru: "У него жар." },
        { en: "Ahmad is calling the nurse.", ru: "Ахмад звонит медсестре." },
        { en: '"I am ill. I cannot work today."', ru: "«Я болен. Я не могу работать сегодня.»" },
        { en: "The nurse is walking to his room.", ru: "Медсестра идёт в его комнату." },
        { en: '"Hello, Ahmad. What is wrong?"', ru: "«Привет, Ахмад. Что случилось?»" },
        { en: '"I have a headache and a fever."', ru: "«У меня болит голова и жар.»" },
        { en: '"I have a cough."', ru: "«У меня кашель.»" },
        { en: "The nurse checks his arm.", ru: "Медсестра осматривает его руку." },
        { en: '"You are ill. You need a doctor."', ru: "«Ты болен. Тебе нужен врач.»" },
        { en: "Ahmad is resting in his room.", ru: "Ахмад отдыхает в своей комнате." },
        { en: "Tom is calling the doctor.", ru: "Том звонит врачу." },
        { en: '"Call 999 in an emergency."', ru: "«Звоните 999 в экстренном случае.»" },
      ],
      glossary: [
        { en: "wrong", transcr: "ронг", ru: "не так, неправильно", pn: "/rɒŋ/" },
        { en: "need", transcr: "нид", ru: "нуждаться, нужно", pn: "/niːd/" },
      ],
      quiz: [
        { q_ru: "Что болит у Ахмада?", opts_ru: ["Голова, и есть жар", "Рука", "Нога", "Зуб"], c: 0 },
        { q_ru: "Кому звонит Ахмад в начале?", opts_ru: ["Медсестре (nurse)", "Врачу", "Тому", "Менеджеру"], c: 0 },
        { q_ru: "Что говорит медсестра про экстренный случай?", opts_ru: ["Звоните 999", "Идите домой", "Ждите утра", "Позвоните Тому"], c: 0 },
      ],
    },
    {
      id: 2, emoji: "🏥", title_ru: "У врача", title_en: "At the doctor",
      sentences: [
        { en: "Ahmad has an appointment.", ru: "У Ахмада запись к врачу." },
        { en: "Tom is driving him to the doctor.", ru: "Том везёт его к врачу." },
        { en: "Ahmad is in the waiting room.", ru: "Ахмад в комнате ожидания." },
        { en: "The doctor is calling his name.", ru: "Врач называет его имя." },
        { en: '"Hello, Ahmad. What is the problem?"', ru: "«Привет, Ахмад. В чём проблема?»" },
        { en: '"I have a pain in my arm."', ru: "«У меня боль в руке.»" },
        { en: '"My arm hurts."', ru: "«Моя рука болит.»" },
        { en: "The doctor is looking at his arm.", ru: "Врач смотрит на его руку." },
        { en: '"Take this plaster, Ahmad."', ru: "«Возьмите этот пластырь, Ахмад.»" },
        { en: '"You need medicine. Go to the chemist."', ru: "«Вам нужно лекарство. Идите в аптеку.»" },
        { en: "Ahmad is going to the chemist.", ru: "Ахмад идёт в аптеку." },
        { en: "He is buying medicine.", ru: "Он покупает лекарство." },
        { en: '"Take this medicine in the morning."', ru: "«Принимайте это лекарство утром.»" },
        { en: "Ahmad is resting at the camp.", ru: "Ахмад отдыхает в лагере." },
        { en: "Ahmad is better the next day.", ru: "На следующий день Ахмаду лучше." },
      ],
      glossary: [
        { en: "need", transcr: "нид", ru: "нуждаться, нужно", pn: "/niːd/" },
      ],
      quiz: [
        { q_ru: "Куда Том везёт Ахмада?", opts_ru: ["К врачу", "В банк", "В поле", "Домой"], c: 0 },
        { q_ru: "Что врач говорит купить Ахмаду?", opts_ru: ["Лекарство (medicine)", "Хлеб", "Карту", "Билет"], c: 0 },
        { q_ru: "Когда принимать лекарство?", opts_ru: ["Утром", "Ночью", "В обед", "В пятницу"], c: 0 },
      ],
    },
    {
      id: 3, emoji: "💷", title_ru: "Мой расчётный лист", title_en: "My payslip",
      sentences: [
        { en: "It is Friday. Ahmad has his payslip.", ru: "Сегодня пятница. У Ахмада расчётный лист." },
        { en: "He is looking at the numbers on the payslip.", ru: "Он смотрит на числа в расчётном листе." },
        { en: '"This is my payslip."', ru: "«Это мой расчётный лист.»" },
        { en: '"My name is here."', ru: "«Здесь моё имя.»" },
        { en: "Ahmad is checking the pay.", ru: "Ахмад проверяет зарплату." },
        { en: '"I have my money on Friday."', ru: "«Я получаю деньги в пятницу.»" },
        { en: "He is counting the pounds.", ru: "Он считает фунты." },
        { en: '"I have 30 pounds in cash."', ru: "«У меня 30 фунтов наличными.»" },
        { en: "Ahmad is asking Tom.", ru: "Ахмад спрашивает Тома." },
        { en: '"Is my overtime here?"', ru: "«Здесь мои сверхурочные?»" },
        { en: "Tom is pointing at the payslip.", ru: "Том указывает на расчётный лист." },
        { en: '"Yes, your overtime pay is here."', ru: "«Да, твои сверхурочные здесь.»" },
        { en: "Ahmad is happy. The pay is correct.", ru: "Ахмад доволен. Зарплата верная." },
        { en: "The payslip is in his bag now.", ru: "Теперь расчётный лист в его сумке." },
        { en: "He is going to the bank.", ru: "Он идёт в банк." },
      ],
      glossary: [
        { en: "correct", transcr: "кэрэкт", ru: "верный, правильный", pn: "/kəˈrekt/" },
      ],
      quiz: [
        { q_ru: "Когда Ахмад получает деньги?", opts_ru: ["В пятницу", "В понедельник", "В субботу", "В воскресенье"], c: 0 },
        { q_ru: "Сколько у Ахмада наличными?", opts_ru: ["30 фунтов", "10 фунтов", "50 фунтов", "5 фунтов"], c: 0 },
        { q_ru: "Какая зарплата у Ахмада?", opts_ru: ["Верная (correct)", "Неверная", "Маленькая", "Нулевая"], c: 0 },
      ],
    },
    {
      id: 4, emoji: "🏧", title_ru: "В банке", title_en: "At the bank",
      sentences: [
        { en: "Ahmad is at the bank.", ru: "Ахмад в банке." },
        { en: "He has his passport.", ru: "У него есть паспорт." },
        { en: "A worker is helping him.", ru: "Сотрудник помогает ему." },
        { en: '"Hello. I need a bank card."', ru: "«Здравствуйте. Мне нужна банковская карта.»" },
        { en: '"What is your name?"', ru: "«Как ваше имя?»" },
        { en: '"My name is Ahmad."', ru: "«Меня зовут Ахмад.»" },
        { en: '"What is your phone number?"', ru: "«Какой ваш номер телефона?»" },
        { en: "Ahmad gives her his phone number.", ru: "Ахмад называет ей свой номер телефона." },
        { en: '"Please sign here."', ru: "«Пожалуйста, подпишите здесь.»" },
        { en: "Ahmad is signing the paper.", ru: "Ахмад подписывает бумагу." },
        { en: '"Your card is ready."', ru: "«Ваша карта готова.»" },
        { en: "Ahmad has money in the bank now.", ru: "Теперь у Ахмада есть деньги в банке." },
        { en: '"How much money is in my bank?"', ru: "«Сколько денег у меня в банке?»" },
        { en: '"You have 50 pounds."', ru: "«У вас 50 фунтов.»" },
        { en: "Ahmad is happy. He has a bank card now.", ru: "Ахмад рад. Теперь у него есть банковская карта." },
      ],
      glossary: [
        { en: "need", transcr: "нид", ru: "нуждаться, нужно", pn: "/niːd/" },
        { en: "paper", transcr: "пэйпэ", ru: "бумага", pn: "/ˈpeɪpə/" },
      ],
      quiz: [
        { q_ru: "Что нужно Ахмаду в банке?", opts_ru: ["Банковская карта", "Паспорт", "Телефон", "Лекарство"], c: 0 },
        { q_ru: "Что Ахмад подписывает?", opts_ru: ["Бумагу (paper)", "Контракт", "Письмо", "Билет"], c: 0 },
        { q_ru: "Сколько денег у Ахмада в банке?", opts_ru: ["50 фунтов", "30 фунтов", "10 фунтов", "100 фунтов"], c: 0 },
      ],
    },
    {
      id: 5, emoji: "📄", title_ru: "Моя анкета", title_en: "My form",
      sentences: [
        { en: "Tom gives Ahmad a form.", ru: "Том даёт Ахмаду анкету." },
        { en: '"Please fill in this form."', ru: "«Пожалуйста, заполните эту анкету.»" },
        { en: "Ahmad is looking at the form.", ru: "Ахмад смотрит на анкету." },
        { en: "He is writing his name on the form.", ru: "Он пишет своё имя в анкете." },
        { en: '"What is your address?"', ru: "«Какой ваш адрес?»" },
        { en: "Ahmad is writing his address.", ru: "Ахмад пишет свой адрес." },
        { en: '"When is your birthday?"', ru: "«Когда у вас день рождения?»" },
        { en: '"My birthday is in March."', ru: "«Мой день рождения в марте.»" },
        { en: "Ahmad is writing his date of birth.", ru: "Ахмад пишет свою дату рождения." },
        { en: '"Is your postcode here?"', ru: "«Ваш почтовый индекс здесь?»" },
        { en: '"Yes, my postcode is here."', ru: "«Да, мой почтовый индекс здесь.»" },
        { en: '"Now please sign here."', ru: "«Теперь, пожалуйста, подпишите здесь.»" },
        { en: "Ahmad is writing his signature.", ru: "Ахмад пишет свою подпись." },
        { en: '"Your form is ready."', ru: "«Ваша анкета готова.»" },
        { en: "Ahmad has the form in his bag now.", ru: "Теперь анкета в сумке Ахмада." },
      ],
      glossary: [
        { en: "writing", transcr: "райтинг", ru: "пишет, писать", pn: "/ˈraɪtɪŋ/" },
        { en: "birth", transcr: "бёс", ru: "рождение", pn: "/bɜːθ/" },
      ],
      quiz: [
        { q_ru: "Что Том даёт Ахмаду заполнить?", opts_ru: ["Анкету (form)", "Контракт", "Письмо", "Карту"], c: 0 },
        { q_ru: "Когда день рождения Ахмада?", opts_ru: ["В марте", "В мае", "В апреле", "В январе"], c: 0 },
        { q_ru: "Что Ахмад пишет в конце?", opts_ru: ["Подпись (signature)", "Адрес", "Имя", "Дату"], c: 0 },
      ],
    },
    {
      id: 6, emoji: "📝", title_ru: "Мой контракт", title_en: "My contract",
      sentences: [
        { en: "Tom gives Ahmad his contract.", ru: "Том даёт Ахмаду его контракт." },
        { en: '"This is your contract."', ru: "«Это ваш контракт.»" },
        { en: "Ahmad is reading the contract.", ru: "Ахмад читает контракт." },
        { en: '"My name is on the contract."', ru: "«Моё имя в контракте.»" },
        { en: '"What are my work hours?"', ru: "«Какие у меня рабочие часы?»" },
        { en: '"Your shift is eight hours a day."', ru: "«Твоя смена — восемь часов в день.»" },
        { en: '"When is pay day?"', ru: "«Когда день выплаты?»" },
        { en: '"Pay day is on Friday."', ru: "«День выплаты — в пятницу.»" },
        { en: "Ahmad is looking at the contract again.", ru: "Ахмад снова смотрит на контракт." },
        { en: '"I am the manager. My name is Tom."', ru: "«Я менеджер. Меня зовут Том.»" },
        { en: '"Please sign the contract here."', ru: "«Пожалуйста, подпишите контракт здесь.»" },
        { en: "Ahmad is signing the contract.", ru: "Ахмад подписывает контракт." },
        { en: '"This is your copy."', ru: "«Это ваша копия.»" },
        { en: "Ahmad has the contract in his bag.", ru: "Теперь контракт в сумке Ахмада." },
        { en: '"Good work, Ahmad!"', ru: "«Хорошая работа, Ахмад!»" },
      ],
      glossary: [
        { en: "again", transcr: "эгэн", ru: "снова, опять", pn: "/əˈɡen/" },
        { en: "copy", transcr: "копи", ru: "копия", pn: "/ˈkɒpi/" },
      ],
      quiz: [
        { q_ru: "Сколько часов длится смена Ахмада?", opts_ru: ["Восемь часов", "Десять часов", "Шесть часов", "Двенадцать часов"], c: 0 },
        { q_ru: "Когда день выплаты?", opts_ru: ["В пятницу", "В понедельник", "В субботу", "В среду"], c: 0 },
        { q_ru: "Что Ахмад получает в конце?", opts_ru: ["Копию контракта (copy)", "Новую анкету", "Расчётный лист", "Карту"], c: 0 },
      ],
    },
  ];

  // Library = shelf of books. Chapters keep a per-book id; "ahmad" is snowball-gated
  // (chapter N unlocks after lesson N), "madina" is a fixed-level book (gate/level = 15).
  const BOOKS = [
    {
      id: "ahmad",
      emoji: "📖",
      title_ru: "История Ахмада",
      title_en: "Ahmad's story",
      sub_ru: "Сезон на ферме — глава за главой",
      chapters: READER,
    },
    {
      id: "madina",
      emoji: "🧕",
      title_ru: "История Мадины",
      title_en: "Madina's story",
      sub_ru: "Первый сезон Мадины · уровень A1",
      gate: 15,   // unlocks as a whole after the A0-A1 course (lesson 15)
      level: 15,  // vocabulary cap = union of lessons 1..15 (fixed A1)
      chapters: MADINA,
    },
    {
      id: "review",
      emoji: "📚",
      title_ru: "История Бобура",
      title_en: "Bobur's story",
      sub_ru: "Лёгкое повторение · уровень A1",
      gate: 15,
      level: 15,
      chapters: BOBUR,
    },
    {
      id: "survival",
      emoji: "🆘",
      title_ru: "Выживание на ферме",
      title_en: "Farm survival guide",
      sub_ru: "Здоровье · деньги · документы · A1",
      gate: 15,
      level: 15,
      chapters: SURVIVAL,
    },
    {
      id: "ahmad3",
      emoji: "🌿",
      title_ru: "Ахмад — третий сезон",
      title_en: "Ahmad: the third season",
      sub_ru: "Третий сезон · уровень A2",
      gate: 23,
      level: 23,
      chapters: AHMAD3,
    },
  ];

  if (typeof module !== "undefined" && module.exports) module.exports = BOOKS;
  else root.BOOKS = BOOKS;
})(typeof window !== "undefined" ? window : globalThis);
